#!/usr/bin/env python3
"""Copy the legal documents into `feature:legal` so the app can read them offline.

**`docs/legal/` is the source of truth.** Nothing here edits a document and nothing edits the
copies by hand: the files under `feature/legal/src/main/assets/legal/` are build output that
happens to be committed, the same way `site/` is. Revise `docs/legal/TERMS.md` or
`docs/legal/PRIVACY_POLICY.md`, run this, commit both.

    python3 scripts/release/sync-legal-documents.py          # write the assets
    python3 scripts/release/sync-legal-documents.py --check   # fail if they are stale

Why assets rather than `strings.xml`: these are documents. They are revised as documents, they are
diffed as documents, and the same text has to reach the published website — which reads the very
same two files through `scripts/site/build-site.py`. Cut into a few hundred string resources they
would be a few hundred chances for a merge or a translation pass to break one line of a legal
instrument, and no way to read the result as prose.

### The privacy policy is two documents in one file

`PRIVACY_POLICY.md` carries the Persian policy, then a rule, then the English one under its own
`# Privacy Policy` heading. On a page — and on a screen — those are two documents: an English
paragraph laid out inside an RTL column has its punctuation on the wrong side and reads badly. So
the file is split at that heading and each half is shipped as its own asset, which is exactly what
the site builder does with it. `values-en/strings.xml` names the English asset, so Android's own
resource qualification picks the right half and the app needs no locale code of its own.

The terms ship in both languages as well: `TERMS.md` is the Persian text and governs, `TERMS_EN.md`
is its English translation and says so in its own opening lines. `values-en/strings.xml` names the
English asset, the same way it names the English half of the privacy policy.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs" / "legal"
TARGET = ROOT / "feature" / "legal" / "src" / "main" / "assets" / "legal"

# The English half begins at its own level-one heading. Matched on the words rather than on the
# whole line because the product name in that heading has changed once already, and a split that
# breaks silently when a brand is renamed is worse than no split at all.
ENGLISH_HEADING = re.compile(r"^# Privacy Policy\b.*$", re.MULTILINE)

# A generated file says so. Readers of a diff should not have to guess which of two identical
# documents is the one to edit, and the answer has to survive being read on its own.
BANNER_FA = (
    "<!-- Generated by scripts/release/sync-legal-documents.py from docs/legal/. "
    "Edit the source, not this copy. -->\n"
)


def split_privacy(text: str) -> tuple[str, str]:
    """The Persian half and the English half, each a whole document."""
    match = ENGLISH_HEADING.search(text)
    if match is None:
        raise SystemExit(
            "LEGAL_SYNC_ERROR: docs/legal/PRIVACY_POLICY.md no longer carries an English "
            "'# Privacy Policy' heading, so it cannot be split into its two documents."
        )
    # The Persian half ends with the pair of horizontal rules that separate the two. They are the
    # seam, not content, and a document that ends on a divider renders with a stray line under it.
    persian = text[: match.start()].rstrip()
    while persian.endswith("-"):
        persian = persian.rstrip("-").rstrip()
    return persian + "\n", text[match.start():]


def documents() -> dict[Path, str]:
    terms = (SOURCE / "TERMS.md").read_text(encoding="utf-8")
    terms_en = (SOURCE / "TERMS_EN.md").read_text(encoding="utf-8")
    persian, english = split_privacy((SOURCE / "PRIVACY_POLICY.md").read_text(encoding="utf-8"))
    return {
        TARGET / "terms.md": BANNER_FA + terms,
        TARGET / "terms-en.md": BANNER_FA + terms_en,
        TARGET / "privacy.md": BANNER_FA + persian,
        TARGET / "privacy-en.md": BANNER_FA + english,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the assets are out of date")
    arguments = parser.parse_args()

    files = documents()
    stale = [
        path
        for path, body in files.items()
        if not path.exists() or path.read_text(encoding="utf-8") != body
    ]

    if arguments.check:
        for path in stale:
            print(f"::error file={path.relative_to(ROOT)}::out of date; run {Path(__file__).relative_to(ROOT)}")
        if stale:
            return 1
        print(f"Legal assets are current: {len(files)} file(s) match docs/legal/.")
        return 0

    TARGET.mkdir(parents=True, exist_ok=True)
    for path, body in files.items():
        path.write_text(body, encoding="utf-8")
    print(f"Wrote {len(files)} legal asset(s) to {TARGET.relative_to(ROOT)}/ from docs/legal/.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
