package com.coinepro.core.datastore

import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.distinctUntilChanged
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map

/**
 * A saved chart setup, under a name the reader chose.
 *
 * Not the drawings. Drawings are anchored to one instrument's price and time and mean nothing on
 * another; a layout is the *apparatus* a reader looks through, and the whole point is that it
 * carries from symbol to symbol. Saving drawings into a layout would paste last week's trend lines
 * onto whatever chart it was applied to. [ChartDrawingStore] makes the opposite decision for the
 * opposite reason.
 *
 * [symbol] is here anyway, and it is not a contradiction of that. It records the chart the layout
 * was *built on*, so a list of layouts can say what each one came from and so [ChartLayoutStore]
 * can offer the right one first when that symbol opens. Applying a layout does not move the chart
 * to its symbol.
 *
 * Every id in here is a plain String for the same reason [SymbolChartState]'s are: `core:datastore`
 * must not depend on `core:chart`, and a string that this build no longer recognises should be
 * ignored rather than crash a reader who downgraded.
 */
data class ChartLayout(
    /** Stable and generated by the caller — a rename must not orphan the row. */
    val id: String,
    /** What the reader typed. Displayed as-is; this module never invents or translates it. */
    val name: String,
    /** The symbol the layout was built on. See the class note: it is provenance, not a target. */
    val symbol: String,
    val timeframe: String,
    val chartType: String,
    /** Indicator ids, in the order the reader added them. */
    val indicators: List<String> = emptyList(),
    /** The period each indicator was configured with, keyed by indicator id. */
    val indicatorPeriods: Map<String, Int> = emptyMap(),
    /** The price-scale mode id. Empty means the layout does not override the app's default. */
    val scaleMode: String = "",
    /** A [ChartColourTemplate.id], or null to keep whatever colours the theme gives. */
    val colourTemplate: String? = null,
    val createdAt: Long = 0L,
    /** Epoch milliseconds. What [ChartLayoutStore.layouts] orders by — newest first. */
    val updatedAt: Long = 0L,
)

/**
 * A set of chart colours the reader can switch between.
 *
 * Colours are ARGB packed into a `Long` rather than Compose `Color` values, because
 * `core:datastore` does not depend on Compose and should not: this file is read by the widget
 * process and by plain unit tests. `Color(value.toULong() shl 32)` on the other side of the
 * boundary is the whole conversion.
 *
 * The names are the fields a Persian chart-settings screen labels one by one. There are no Persian
 * strings in this module — it is a storage layer, and the labels belong in the feature module that
 * draws them.
 */
data class ChartColourTemplate(
    val id: String,
    /**
     * The reader's own name for a template they made.
     *
     * The two built-ins carry machine names — `dark` and `light` — rather than Persian ones,
     * because a storage layer that ships user-facing text ships it in one language and then has to
     * be migrated when that changes. The feature module maps [BUILT_IN_DARK_ID] and
     * [BUILT_IN_LIGHT_ID] to whatever it wants to call them on screen.
     */
    val name: String,
    /** A rising candle, and every gain figure drawn on the chart. */
    val up: Long,
    /** A falling candle. */
    val down: Long,
    /** The grid rules behind the series. */
    val grid: Long,
    /** The ground the chart draws on. */
    val background: Long,
    /** Axis labels and the price tags. */
    val text: Long,
    /** The crosshair the reader drags, and its readout rails. */
    val crosshair: Long,
) {
    /** Whether this template ships with the app, and so cannot be deleted or overwritten. */
    val isBuiltIn: Boolean get() = id == BUILT_IN_DARK_ID || id == BUILT_IN_LIGHT_ID

    companion object {
        const val BUILT_IN_DARK_ID = "builtin_dark"
        const val BUILT_IN_LIGHT_ID = "builtin_light"

        /**
         * The dark template, on this app's own market palette.
         *
         * Every value is lifted from `CoineProDarkPalette` in `core:designsystem` rather than
         * invented here — `buy`, `sell`, `terminal` (the chart ground, which is deliberately a
         * step darker than the page), `surfaceOverlay` for the grid, `textSecondary` for axis ink
         * and `textMuted` for the crosshair. Copied rather than depended on, because a
         * preferences module has no business importing Compose; if the palette moves, this moves
         * with it.
         */
        val Dark = ChartColourTemplate(
            id = BUILT_IN_DARK_ID,
            name = "dark",
            up = 0xFF00B15C,
            down = 0xFFF6465D,
            grid = 0xFF1E2329,
            background = 0xFF070A0F,
            text = 0xFFB7BDC6,
            crosshair = 0xFF848E9C,
        )

        /**
         * The light template, on the same palette's light values.
         *
         * The green and the red are darkened well past their dark-theme pair on purpose: the
         * greens that carry a gain on near-black measure under 2:1 on white. That is
         * `CoineProLightPalette`'s reasoning and this inherits it rather than re-deciding it.
         */
        val Light = ChartColourTemplate(
            id = BUILT_IN_LIGHT_ID,
            name = "light",
            up = 0xFF0E8A4C,
            down = 0xFFC9203A,
            grid = 0xFFE8EBEF,
            background = 0xFFF7F8FA,
            text = 0xFF4E5661,
            crosshair = 0xFF707A88,
        )

        /** The templates that always exist. Listed before anything the reader made. */
        val BUILT_IN = listOf(Dark, Light)
    }
}

/**
 * The reader's own layouts, their colour templates, and which layout the chart should come back to.
 *
 * ### There is no limit on how many layouts a reader may keep
 *
 * That is a product decision, not an oversight. The obvious competitor's free tier allows exactly
 * one saved layout, and charging for the second is one of the things this app deliberately does
 * not do. [MAX_LAYOUTS] exists only so that a bug in a caller — a save inside a recomposition, say
 * — cannot grow this string without bound; it sits at five hundred, which no person reaches and no
 * runaway loop stays under.
 *
 * ### The encoding
 *
 * The delimited-string scheme [ChartDrawingStore] and [SymbolChartStateStore] use, for the same
 * reason: the alternative is a serialisation library in a preferences module. ASCII's group
 * separator between records, its record separator between one record's fields, its unit separator
 * inside the indicator list and the period map. All three are control characters, so nothing a
 * reader can type contains one — and [encodeLayout] refuses a name that somehow does rather than
 * writing a record that would parse back as different fields. Refused rather than sanitised:
 * silently renaming somebody's layout is worse than not saving it.
 *
 * Decoding never throws. A record from an older build is short and its missing fields take their
 * defaults; a record from a newer build has trailing fields this version ignores. Only a record
 * with no id is dropped, because nothing can address it.
 *
 * ### Why the preferences key is not `chart_layouts`
 *
 * It is [LAYOUTS], `chart_layouts_v2`. The first version of this store wrote four fields in a
 * different order, and those records would decode under this one as a layout whose id is the old
 * name and whose timeframe is an indicator list. A new key leaves them where they are instead of
 * reading them wrong; the cost is that a reader upgrading loses layouts they saved under the old
 * shape, which is the smaller of the two harms and the honest one.
 */
class ChartLayoutStore(private val dataStore: DataStore<Preferences>) {

    /**
     * Every saved layout, newest first.
     *
     * Ordered by [ChartLayout.updatedAt] rather than by name, because the list is read as a
     * history — the layout somebody was last working in is the one they want at the top, and a
     * rename should move it there.
     */
    fun layouts(): Flow<List<ChartLayout>> = dataStore.data
        .map { preferences -> decodeLayouts(preferences[LAYOUTS].orEmpty()) }
        .distinctUntilChanged()

    /** Writes a layout, replacing any layout with the same [ChartLayout.id]. */
    suspend fun save(layout: ChartLayout) {
        if (encodeLayout(layout) == null) return
        dataStore.edit { preferences ->
            val kept = decodeLayouts(preferences[LAYOUTS].orEmpty()).filterNot { it.id == layout.id }
            preferences[LAYOUTS] = (kept + layout)
                .sortedByDescending(ChartLayout::updatedAt)
                .take(MAX_LAYOUTS)
                .mapNotNull { encodeLayout(it) }
                .joinToString(GROUP)
        }
    }

    /**
     * Renames one layout in place, keeping its id and everything under it.
     *
     * Its own operation rather than a [save] of a copied row, because the caller doing that would
     * have to read the layout first and would race a concurrent edit of the same row. A blank name
     * or one carrying a separator is refused and the stored name stands.
     */
    suspend fun rename(id: String, name: String) {
        if (name.isBlank() || hasSeparator(name)) return
        dataStore.edit { preferences ->
            val existing = decodeLayouts(preferences[LAYOUTS].orEmpty())
            if (existing.none { it.id == id }) return@edit
            preferences[LAYOUTS] = existing
                .map { if (it.id == id) it.copy(name = name) else it }
                .mapNotNull { encodeLayout(it) }
                .joinToString(GROUP)
        }
    }

    /** Removes one layout, and clears [lastOpened] if it pointed at that layout. */
    suspend fun delete(id: String) {
        dataStore.edit { preferences ->
            val kept = decodeLayouts(preferences[LAYOUTS].orEmpty()).filterNot { it.id == id }
            if (kept.isEmpty()) {
                preferences.remove(LAYOUTS)
            } else {
                preferences[LAYOUTS] = kept.mapNotNull { encodeLayout(it) }.joinToString(GROUP)
            }
            // A dangling last-opened id would send the next chart open looking for a layout that
            // is not there, and the recovery from that is indistinguishable from never having set
            // one — so it is cleared here rather than tolerated there.
            if (preferences[LAST_OPENED] == id) preferences.remove(LAST_OPENED)
        }
    }

    /** One layout by id, or null. A single read, for a caller with nothing to collect a flow in. */
    suspend fun get(id: String): ChartLayout? = layouts().first().firstOrNull { it.id == id }

    /**
     * The layout the chart should restore when it opens, or null if the reader has not used one.
     *
     * Stored as an id rather than as a copy of the layout, so that editing a layout changes what
     * reopening restores — which is what somebody who just adjusted their setup expects.
     */
    fun lastOpened(): Flow<String?> = dataStore.data
        .map { preferences -> preferences[LAST_OPENED]?.takeIf(String::isNotBlank) }
        .distinctUntilChanged()

    /** Records the layout in use, or clears it when passed null. */
    suspend fun setLastOpened(id: String?) {
        dataStore.edit { preferences ->
            val trimmed = id?.takeIf { it.isNotBlank() && !hasSeparator(it) }
            if (trimmed == null) {
                preferences.remove(LAST_OPENED)
            } else {
                preferences[LAST_OPENED] = trimmed
            }
        }
    }

    /**
     * Every colour template: the two that ship with the app first, then the reader's own.
     *
     * Built-ins are prepended at read time rather than written to disk on first launch. Writing
     * them would freeze whatever their colours were on the day the app was installed, so a fix to
     * the palette would never reach anybody who had already run the app once.
     */
    fun templates(): Flow<List<ChartColourTemplate>> = dataStore.data
        .map { preferences ->
            ChartColourTemplate.BUILT_IN + decodeTemplates(preferences[TEMPLATES].orEmpty())
        }
        .distinctUntilChanged()

    /**
     * Writes a template, replacing any with the same id.
     *
     * A built-in's id is refused. Allowing it would let a stored row shadow the shipped one, and
     * then a reader whose custom colours are unreadable would have no way back to the default that
     * is supposed to be always there.
     */
    suspend fun saveTemplate(template: ChartColourTemplate) {
        if (template.isBuiltIn || encodeTemplate(template) == null) return
        dataStore.edit { preferences ->
            val kept = decodeTemplates(preferences[TEMPLATES].orEmpty()).filterNot { it.id == template.id }
            // takeLast rather than take: at the cap the row just written has to be the one that
            // survives, or saving would silently do nothing.
            preferences[TEMPLATES] = (kept + template)
                .takeLast(MAX_TEMPLATES)
                .mapNotNull { encodeTemplate(it) }
                .joinToString(GROUP)
        }
    }

    /**
     * Removes one of the reader's templates.
     *
     * The two built-ins cannot be deleted, and the call is a no-op rather than an error: the
     * caller's job is to not offer the button, and a storage layer refusing loudly would just make
     * that a crash instead of a missing menu item.
     */
    suspend fun deleteTemplate(id: String) {
        if (id == ChartColourTemplate.BUILT_IN_DARK_ID || id == ChartColourTemplate.BUILT_IN_LIGHT_ID) return
        dataStore.edit { preferences ->
            val kept = decodeTemplates(preferences[TEMPLATES].orEmpty()).filterNot { it.id == id }
            if (kept.isEmpty()) {
                preferences.remove(TEMPLATES)
            } else {
                preferences[TEMPLATES] = kept.mapNotNull { encodeTemplate(it) }.joinToString(GROUP)
            }
        }
    }

    companion object {
        /** See the class note on why this is not `chart_layouts`. */
        internal val LAYOUTS = stringPreferencesKey("chart_layouts_v2")
        internal val TEMPLATES = stringPreferencesKey("chart_colour_templates")
        internal val LAST_OPENED = stringPreferencesKey("chart_last_opened_layout")

        /** Between records. ASCII group separator. */
        private const val GROUP = "\u001D"

        /** Between one record's fields. ASCII record separator. */
        private const val RECORD = "\u001E"

        /** Inside the indicator list and the period map. ASCII unit separator. */
        private const val UNIT = "\u001F"

        /**
         * A sanity cap, not a product limit. See the class note: layouts are deliberately
         * unlimited, and this number exists only so a caller stuck in a loop cannot grow one
         * preferences string until the file is unreadable.
         */
        const val MAX_LAYOUTS = 500

        /** The same sanity cap, for templates, which nobody makes hundreds of either. */
        const val MAX_TEMPLATES = 100

        internal fun encodeLayout(layout: ChartLayout): String? {
            if (layout.id.isBlank() || hasSeparator(layout.id)) return null
            if (layout.name.isBlank() || hasSeparator(layout.name)) return null
            val indicators = layout.indicators.filterNot { hasSeparator(it) }
            val periods = layout.indicatorPeriods
                .filterKeys { !hasSeparator(it) }
                .flatMap { (id, period) -> listOf(id, period.toString()) }
            return listOf(
                layout.id,
                layout.name,
                blankIfSeparated(layout.symbol),
                blankIfSeparated(layout.timeframe),
                blankIfSeparated(layout.chartType),
                indicators.joinToString(UNIT),
                periods.joinToString(UNIT),
                blankIfSeparated(layout.scaleMode),
                blankIfSeparated(layout.colourTemplate.orEmpty()),
                layout.createdAt.toString(),
                layout.updatedAt.toString(),
            ).joinToString(RECORD)
        }

        internal fun decodeLayouts(stored: String): List<ChartLayout> = stored
            .split(GROUP)
            .filter(String::isNotBlank)
            .mapNotNull { decodeLayout(it) }
            .sortedByDescending(ChartLayout::updatedAt)

        internal fun decodeLayout(record: String): ChartLayout? {
            val parts = record.split(RECORD)
            val id = parts.getOrNull(0)?.takeIf(String::isNotBlank) ?: return null
            val periodParts = parts.getOrNull(6).orEmpty().split(UNIT).filter(String::isNotBlank)
            return ChartLayout(
                id = id,
                // A row saved before names were required reads back under its own id rather than
                // as a blank row the reader cannot tell apart from its neighbours.
                name = parts.getOrNull(1)?.takeIf(String::isNotBlank) ?: id,
                symbol = parts.getOrNull(2).orEmpty(),
                timeframe = parts.getOrNull(3).orEmpty(),
                chartType = parts.getOrNull(4).orEmpty(),
                indicators = parts.getOrNull(5).orEmpty().split(UNIT).filter(String::isNotBlank),
                indicatorPeriods = periodParts
                    // Alternating id and period. A trailing id with no number drops that entry
                    // rather than shifting every pair after it by one.
                    .chunked(2)
                    .mapNotNull { pair ->
                        if (pair.size != 2) return@mapNotNull null
                        val period = pair[1].toIntOrNull() ?: return@mapNotNull null
                        pair[0] to period
                    }
                    .toMap(),
                scaleMode = parts.getOrNull(7).orEmpty(),
                colourTemplate = parts.getOrNull(8)?.takeIf(String::isNotBlank),
                createdAt = parts.getOrNull(9)?.toLongOrNull() ?: 0L,
                updatedAt = parts.getOrNull(10)?.toLongOrNull() ?: 0L,
            )
        }

        internal fun encodeTemplate(template: ChartColourTemplate): String? {
            if (template.id.isBlank() || hasSeparator(template.id)) return null
            if (template.name.isBlank() || hasSeparator(template.name)) return null
            return listOf(
                template.id,
                template.name,
                template.up.toString(),
                template.down.toString(),
                template.grid.toString(),
                template.background.toString(),
                template.text.toString(),
                template.crosshair.toString(),
            ).joinToString(RECORD)
        }

        internal fun decodeTemplates(stored: String): List<ChartColourTemplate> = stored
            .split(GROUP)
            .filter(String::isNotBlank)
            .mapNotNull { decodeTemplate(it) }

        internal fun decodeTemplate(record: String): ChartColourTemplate? {
            val parts = record.split(RECORD)
            val id = parts.getOrNull(0)?.takeIf(String::isNotBlank) ?: return null
            // A colour that will not parse falls back to the dark built-in's, which is a readable
            // chart with one wrong hue — the alternative, dropping the row, is a template that
            // vanishes from the list with nothing to say why.
            return ChartColourTemplate(
                id = id,
                name = parts.getOrNull(1)?.takeIf(String::isNotBlank) ?: id,
                up = parts.getOrNull(2)?.toLongOrNull() ?: ChartColourTemplate.Dark.up,
                down = parts.getOrNull(3)?.toLongOrNull() ?: ChartColourTemplate.Dark.down,
                grid = parts.getOrNull(4)?.toLongOrNull() ?: ChartColourTemplate.Dark.grid,
                background = parts.getOrNull(5)?.toLongOrNull() ?: ChartColourTemplate.Dark.background,
                text = parts.getOrNull(6)?.toLongOrNull() ?: ChartColourTemplate.Dark.text,
                crosshair = parts.getOrNull(7)?.toLongOrNull() ?: ChartColourTemplate.Dark.crosshair,
            )
        }

        /**
         * A plain function rather than an extension, so that the instance methods above can call
         * it by name without pulling the companion in as a receiver.
         */
        private fun hasSeparator(value: String) =
            value.contains(GROUP) || value.contains(RECORD) || value.contains(UNIT)

        /** A separator inside a free field would shift every field after it. Blanked instead. */
        private fun blankIfSeparated(value: String) = if (hasSeparator(value)) "" else value
    }
}
