package com.coinepro.core.datastore

import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.distinctUntilChanged
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map

/**
 * A named set of indicators, and nothing else.
 *
 * ### Why this is not a layout
 *
 * [ChartLayout] already saves indicators — along with the timeframe, the chart type, the scale mode
 * and the colours. That is the right thing for "put my chart back the way it was" and the wrong
 * thing for "add my momentum set to *this* chart": applying a layout to a four-hour candle chart
 * because it happens to carry the indicators somebody wanted throws them back onto the fifteen
 * minute line chart the layout was saved from. Readers hit that today, notice the timeframe jump,
 * and stop using saved layouts for the thing they most wanted them for.
 *
 * So a template carries the indicators, their periods and their sources, and deliberately carries
 * no timeframe, no chart type, no scale mode and no colour template. Applying one changes what is
 * drawn *on* the chart and never what the chart is.
 *
 * ### Every id in here is a plain String
 *
 * The same rule [SymbolChartState] and [ChartLayout] give: `core:datastore` must not depend on
 * `core:chart`, and it does not. An indicator is an id the catalogue already keys on, and an id
 * this build no longer recognises stays on disk and is simply never resolved — which is what
 * should happen when an indicator is renamed or somebody downgrades.
 *
 * [sources] is the same decision taken one step further. It carries indicator-on-indicator
 * chaining — an RSI computed on an EMA rather than on close — and this module stores both halves
 * as opaque strings without knowing what a source *is*. That is not laziness: the grammar of a
 * source is still being settled in the chart engine, and a storage layer that understood it would
 * have to be revised every time it changed, on disk, for readers who had already saved templates.
 * Storing it as text means a source spelling this build has never seen round-trips untouched.
 *
 * [createdAt] is epoch milliseconds and is load-bearing rather than informational: it is the order
 * the list comes back in and the order the sanity cap evicts by, so a caller that leaves it at zero
 * is saying this template is the first to be thrown away.
 */
data class IndicatorTemplate(
    /** Stable and generated by the caller — a rename must not orphan the row. */
    val id: String,
    /** What the reader typed. Displayed as-is; this module never invents or translates it. */
    val name: String,
    /** Indicator ids, in the order the reader added them. That order is the draw order. */
    val indicators: List<String> = emptyList(),
    /**
     * The period each indicator was configured with, keyed by indicator id.
     *
     * Separate from [indicators] rather than folded into it, for the reason
     * [SymbolChartState.indicatorPeriods] gives: an indicator can be switched off and back on and
     * should return with the period the reader set rather than the catalogue default. An indicator
     * with no entry here is applied at its default, which is also what every template written
     * before it gained a period reads back as.
     */
    val periods: Map<String, Int> = emptyMap(),
    /**
     * What each indicator is computed on, keyed by indicator id — an opaque string. See the class
     * note: this module stores the chaining and deliberately does not understand it.
     */
    val sources: Map<String, String> = emptyMap(),
    /** Epoch milliseconds. Newest first is the order the reader sees. */
    val createdAt: Long = 0L,
)

/**
 * The reader's indicator templates.
 *
 * ### There is no limit on how many a reader may keep, and that is the point
 *
 * TradingView's free tier allows exactly **one** indicator template and charges for the second.
 * That limit is precisely the thing this file exists to remove, so there is no product cap here at
 * all — a reader may save a template per strategy, per market, per session, for years.
 * [MAX_TEMPLATES] is two hundred and is a *sanity* cap in the sense [WatchlistStore.MAX_LISTS] is:
 * it exists so a caller stuck in a loop cannot grow one preferences string without bound, not to
 * price anybody out of the second one. Nobody reaches two hundred by hand and no runaway stays
 * under it.
 *
 * ### One preferences entry
 *
 * Every template is packed into a single string the way [SymbolChartStateStore] packs symbols,
 * because each of this store's jobs — [templates], [get], evicting the oldest — needs to see every
 * row at once, and a preferences file cannot enumerate keys by prefix without reading the whole
 * file anyway.
 *
 * ### The encoding
 *
 * The delimited-string scheme [ChartDrawingStore] and [DrawingTemplateStore] use, for the same
 * reason: the alternative is a serialisation library in a preferences module. ASCII's group
 * separator between templates, its record separator between one template's fields, its unit
 * separator inside the indicator list, the period map and the source map. All three are control
 * characters, so no id the app generates can contain one, and a name that does is written with the
 * separator stripped rather than as a record that would parse back as different fields.
 *
 * ### Decoding never throws, and short rows are the point
 *
 * A row written by an older build is *short* — fewer fields than this version writes — and every
 * missing field takes its default rather than discarding the row. Only [IndicatorTemplate.id] is
 * required, because a row nothing can address belongs to nothing. A row written by a *newer* build
 * carries fields this version has never heard of, and those are ignored rather than treated as
 * corruption; that is how [IndicatorTemplate.sources] arrived, on the end, and how the next field
 * has to arrive too. Nothing already written is ever reinterpreted. The failure this avoids is the
 * one that matters — a reader who updates the app and finds their saved sets gone.
 */
class IndicatorTemplateStore(private val dataStore: DataStore<Preferences>) {

    /**
     * Every template, newest first.
     *
     * Newest first because that is also the order the sanity cap evicts in, so what sits at the
     * bottom of the reader's list is what would go if they ever reached two hundred.
     * Distinct-until-changed because an open chart collects this while unrelated preferences are
     * being written next to it.
     */
    fun templates(): Flow<List<IndicatorTemplate>> = dataStore.data
        .map { preferences -> decodeAll(preferences[TEMPLATES].orEmpty()) }
        .distinctUntilChanged()

    /**
     * One template by id, or null if it is not there.
     *
     * A one-shot read rather than a `Flow`, because applying a template is an event: the caller
     * wants the set as it stands at the moment of the tap and has no interest in being told about
     * it again afterwards. A screen that lists templates collects [templates] instead.
     */
    suspend fun get(id: String): IndicatorTemplate? =
        decodeAll(dataStore.data.first()[TEMPLATES].orEmpty()).firstOrNull { it.id == id }

    /**
     * Writes one template, replacing whatever was stored under the same id.
     *
     * An upsert rather than an append, so the edit sheet can save the same template repeatedly
     * without the list growing a copy each time. A template with a blank id is dropped: nothing
     * could ever apply it, and storing it would put a row in the reader's list that does nothing
     * when tapped.
     *
     * A template with **no** indicators is stored, deliberately. "Clear every indicator" is a set a
     * reader can reasonably name and reach for, and refusing to save it would be this file deciding
     * which of the reader's sets are worth keeping.
     */
    suspend fun save(template: IndicatorTemplate) {
        if (encode(template) == null) return
        dataStore.edit { preferences ->
            val kept = decodeAll(preferences[TEMPLATES].orEmpty()).filterNot { it.id == template.id }
            preferences[TEMPLATES] = write(kept + template)
        }
    }

    /**
     * Renames one template and changes nothing else.
     *
     * Its own operation rather than a [save] of a copied row, because renaming is the one edit that
     * must not disturb [IndicatorTemplate.createdAt] — a reader fixing a typo does not expect the
     * template to jump to the top of their list, or to outlive an older one at the cap.
     */
    suspend fun rename(id: String, name: String) {
        dataStore.edit { preferences ->
            val templates = decodeAll(preferences[TEMPLATES].orEmpty())
            if (templates.none { it.id == id }) return@edit
            preferences[TEMPLATES] = write(
                templates.map { if (it.id == id) it.copy(name = name) else it },
            )
        }
    }

    /** Forgets one template. Deleting the last one removes the entry rather than blanking it. */
    suspend fun delete(id: String) {
        dataStore.edit { preferences ->
            val kept = decodeAll(preferences[TEMPLATES].orEmpty()).filterNot { it.id == id }
            if (kept.isEmpty()) {
                // Removed rather than stored as an empty string, so a reader who deletes their last
                // template leaves nothing behind for the next version to have to parse.
                preferences.remove(TEMPLATES)
            } else {
                preferences[TEMPLATES] = write(kept)
            }
        }
    }

    companion object {
        internal val TEMPLATES = stringPreferencesKey("indicator_templates")

        /** Between templates. ASCII group separator. */
        private const val GROUP = "\u001D"

        /** Between one template's fields. ASCII record separator. */
        private const val RECORD = "\u001E"

        /** Inside the indicator list, the period map and the source map. ASCII unit separator. */
        private const val UNIT = "\u001F"

        /**
         * A bound on a runaway writer, and explicitly not a product limit. See the class note: the
         * competitor's free tier allows one, and removing that is why this file exists.
         */
        const val MAX_TEMPLATES = 200

        /** Newest first, capped, dropping anything that cannot be written back. */
        private fun write(templates: List<IndicatorTemplate>): String = templates
            .sortedByDescending(IndicatorTemplate::createdAt)
            .take(MAX_TEMPLATES)
            .mapNotNull { encode(it) }
            .joinToString(GROUP)

        internal fun encode(template: IndicatorTemplate): String? {
            val id = template.id.takeIf { it.isNotBlank() && !hasSeparator(it) } ?: return null
            // An id carrying a separator is dropped on its own rather than taking the row with it:
            // losing one indicator is a smaller failure than losing the reader's whole set, and no
            // id the app itself generates can contain a control character anyway.
            val indicators = template.indicators.filterNot(::hasSeparator).distinct()
            val periods = template.periods
                .filterKeys { !hasSeparator(it) }
                .flatMap { (indicator, period) -> listOf(indicator, period.toString()) }
            val sources = template.sources
                .filterKeys { !hasSeparator(it) }
                .filterValues { it.isNotBlank() && !hasSeparator(it) }
                .flatMap { (indicator, source) -> listOf(indicator, source) }
            return listOf(
                id,
                // The name is the reader's own text, so it is the one field that can carry a
                // separator. Stripped rather than dropping the template with it: losing the name of
                // a set is a smaller failure than losing the set.
                stripSeparators(template.name),
                indicators.joinToString(UNIT),
                periods.joinToString(UNIT),
                sources.joinToString(UNIT),
                template.createdAt.toString(),
            ).joinToString(RECORD)
        }

        internal fun decodeAll(stored: String): List<IndicatorTemplate> = stored
            .split(GROUP)
            .filter(String::isNotBlank)
            .mapNotNull { decode(it) }
            .sortedByDescending(IndicatorTemplate::createdAt)

        internal fun decode(record: String): IndicatorTemplate? {
            val parts = record.split(RECORD)
            // Only the id is required. Every other field takes its default when a shorter row — one
            // written before that field existed — does not carry it.
            val id = parts.getOrNull(0)?.takeIf(String::isNotBlank) ?: return null
            return IndicatorTemplate(
                id = id,
                name = parts.getOrNull(1).orEmpty(),
                indicators = parts.getOrNull(2).orEmpty().split(UNIT).filter(String::isNotBlank),
                periods = pairs(parts.getOrNull(3))
                    .mapNotNull { (indicator, period) ->
                        val value = period.toIntOrNull() ?: return@mapNotNull null
                        indicator to value
                    }
                    .toMap(),
                sources = pairs(parts.getOrNull(4)).toMap(),
                createdAt = parts.getOrNull(5)?.toLongOrNull() ?: 0L,
            )
        }

        /**
         * An alternating id-and-value field, read as pairs.
         *
         * A trailing id with no value — a half-written record, or one truncated by an older writer
         * — drops that entry and keeps the rest, rather than shifting every pair after it by one
         * and silently giving an indicator somebody else's period.
         */
        private fun pairs(field: String?): List<Pair<String, String>> = field.orEmpty()
            .split(UNIT)
            .filter(String::isNotBlank)
            .chunked(2)
            .mapNotNull { pair -> if (pair.size == 2) pair[0] to pair[1] else null }

        private fun hasSeparator(value: String) =
            value.contains(GROUP) || value.contains(RECORD) || value.contains(UNIT)

        private fun stripSeparators(value: String) =
            value.filterNot { it == GROUP[0] || it == RECORD[0] || it == UNIT[0] }
    }
}
