package com.coinepro.core.datastore

import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import com.coinepro.core.model.MarketPlatform
import java.util.UUID
import java.util.concurrent.atomic.AtomicReference
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking

/**
 * A random identifier for this install, sent so a rate limiter has something better than an IP.
 *
 * Iranian mobile networks put very large numbers of subscribers behind carrier-grade NAT, so a
 * per-IP limit on sign-in is not a limit on one person — it is a limit shared by a whole city, and
 * at peak hours one user's retries lock out everyone else on the same address. An install id gives
 * the server a key that separates them.
 *
 * It is worth being exact about what this is not. The value is generated by the client and stored
 * by the client, so anyone determined to get a fresh bucket can clear the app's data and have one.
 * That makes it a way to keep ordinary users from colliding, **not** a security control, and the
 * server must not treat it as identity or let it stand in for authentication.
 *
 * It is also not a device identifier: it is a random UUID with nothing derived from the hardware,
 * it never leaves the app's private storage except as this one header, and uninstalling the app
 * ends it. Nothing about the user or the device can be recovered from it.
 *
 * Each platform gets its own id. CoinePro-FX and TradeYar are separate accounts on separate
 * servers, and the rule the rest of the app is built on — that neither ever learns anything about
 * the user's business with the other — would be quietly broken by a single shared identifier that
 * let the two correlate one person across both. Separate ids serve the limiter just as well,
 * because each server only ever sees its own.
 */
class InstallIdStore(private val dataStore: DataStore<Preferences>) {
    private val cache = AtomicReference<Map<MarketPlatform, String>>(emptyMap())

    /**
     * Returns the stored id, creating one on first use.
     *
     * The read and the create happen inside a single [edit] so two callers racing at startup cannot
     * mint two ids and have one of them silently win — the app would then present a different
     * identifier on the next launch and the limiter would see two users.
     */
    suspend fun installId(platform: MarketPlatform): String {
        cache.get()[platform]?.let { return it }

        val key = stringPreferencesKey("install_id_${platform.id}")
        val stored = dataStore.data.first()[key]
        val id = stored ?: dataStore.edit { preferences ->
            preferences[key] = preferences[key] ?: UUID.randomUUID().toString()
        }[key]!!

        cache.updateAndGet { it + (platform to id) }
        return id
    }

    /** The value already in memory, or null before [installId] has ever completed for [platform]. */
    fun cached(platform: MarketPlatform): String? = cache.get()[platform]

    /**
     * A blocking accessor for the HTTP interceptor, which has no coroutine to suspend in.
     *
     * Blocking is safe and deliberate here: interceptors run on OkHttp's own dispatcher threads,
     * never the main thread, and this reaches disk at most once per platform per process — every
     * later call is answered from [cache]. Priming it in the background instead would leave the
     * header off exactly the requests that need it most, since sign-in is the first call the app
     * makes and the one the limiter is aimed at.
     *
     * A failed read yields null rather than an exception. The identifier is a courtesy to the
     * limiter; losing it must never cost the user their request.
     */
    fun providerFor(platform: MarketPlatform): () -> String? = {
        cached(platform) ?: runCatching { runBlocking { installId(platform) } }.getOrNull()
    }
}
