package com.coinepro.core.script

/**
 * One shipped strategy: a name, a sentence, and a script that marks both directions (run Σ, S3 F).
 *
 * ### Why the source is generated rather than written out
 *
 * Because the brief asks for sixty strategies **and the same sixty in English**, and a hand-written
 * pair would be a hundred and twenty scripts to keep in step. They would not stay in step. So each
 * entry carries the *parts* that differ — the titles a reader sees, the sentence each signal says —
 * and [source] assembles them into the one shape every strategy in this library has:
 *
 * ```
 * <the reader's inputs>
 * <the study's own lines>
 * risk = ta.atr(14) * riskMultiple
 * stopLine = iff(bias, close - risk, close + risk)
 * <the plots>
 * plot(stopLine, ..., stepped = true)
 * up   = (<up>) and confirmed
 * down = (<down>) and confirmed
 * signal(up, text = "…")
 * signal(down, buy = false, text = "…")
 * ```
 *
 * That shape is not a convenience: it is the contract the rest of the app reads. `signal(...)` is
 * what earns a strategy its confidence percentage and its Explain sheet, `and confirmed` is what
 * stops a mark appearing on the bar still forming and then moving, and [stopAtr] is the default
 * stop the brief asks every strategy to carry — drawn, stepped, on the chart, rather than written
 * in a description nobody reads.
 *
 * ### Why `and confirmed` is not optional
 *
 * It is the fault every script in the old library had. An entry condition evaluated on the forming
 * bar paints an arrow that may be gone a minute later, and a reader who scrolls back sees arrows
 * only on the turns that worked. `ScriptLibraryContentTest` fails on a strategy whose conditions
 * do not end with it.
 */
data class ScriptLibraryEntry(
    /** Repository-owned identity. A reader who saved a copy remembers where it came from. */
    val id: String,
    val family: ScriptFamily,
    val title: String,
    val titleEn: String,
    /** One line, under the title in the library. */
    val summary: String,
    val summaryEn: String,
    /** The default stop, in ATRs. Drawn on the chart; the reader can change it. */
    val stopAtr: Int,
    val inputs: List<ScriptLibraryInput>,
    /** The study's own working, in order. Code only — no text a reader would ever see. */
    val lines: List<String>,
    val plots: List<ScriptLibraryPlot>,
    /** The condition that says the strategy is long-biased; it decides which side the stop is on. */
    val bias: String,
    val up: String,
    val down: String,
    val upText: String,
    val upTextEn: String,
    val downText: String,
    val downTextEn: String,
) {

    fun source(english: Boolean = false): String = buildString {
        for (input in inputs) appendLine(input.line(english))
        appendLine(
            "riskMultiple = input($stopAtr, title = " + quoted(if (english) "Stop in ATRs" else "حد ضرر (ATR)") +
                ", min = 1, max = 10)",
        )
        for (line in lines) appendLine(line)
        appendLine("risk = ta.atr(14) * riskMultiple")
        appendLine("bias = $bias")
        appendLine("stopLine = iff(bias, close - risk, close + risk)")
        for (plot in plots) appendLine(plot.line(english))
        appendLine(
            "plot(stopLine, title = " + quoted(if (english) "Stop" else "حد ضرر") +
                ", color = color.grey, stepped = true)",
        )
        appendLine("up = ($up) and confirmed")
        appendLine("down = ($down) and confirmed")
        appendLine("signal(up, text = " + quoted(if (english) upTextEn else upText) + ")")
        appendLine("signal(down, buy = false, text = " + quoted(if (english) downTextEn else downText) + ")")
    }

    fun title(english: Boolean): String = if (english) titleEn else title

    fun summary(english: Boolean): String = if (english) summaryEn else summary
}

/** What a strategy is about. The library's six shelves. */
enum class ScriptFamily { TREND, MOMENTUM, BREAKOUT, REVERSION, VOLUME, SMART_MONEY }

/** One knob, named in both languages. */
data class ScriptLibraryInput(
    val name: String,
    val default: Int,
    val title: String,
    val titleEn: String,
    val min: Int,
    val max: Int,
) {
    fun line(english: Boolean): String =
        "$name = input($default, title = " + quoted(if (english) titleEn else title) + ", min = $min, max = $max)"
}

/** One line on the chart, named in both languages. */
data class ScriptLibraryPlot(
    val expression: String,
    val title: String,
    val titleEn: String,
    val colour: String,
    /** `"price"` over the candles, `"own"` in a panel of its own. */
    val pane: String,
) {
    fun line(english: Boolean): String =
        "plot($expression, title = " + quoted(if (english) titleEn else title) +
            ", color = $colour, pane = \"$pane\")"
}

/** A title as a NamaScript string literal. */
private fun quoted(text: String): String = "\"" + text.replace("\"", "") + "\""

/**
 * The sixty.
 *
 * Six shelves, because that is how a reader looks for one: «something that follows a trend»,
 * «something that tells me it has gone too far». Not by indicator name — a reader who knows they
 * want the Klinger oscillator does not need a library.
 */
object ScriptLibrary {

    val ALL: List<ScriptLibraryEntry> = listOf(
        ScriptLibraryEntry(
            id = "ema-cross",
            family = ScriptFamily.TREND,
            title = "تقاطع دو میانگین نمایی",
            titleEn = "Two EMAs cross",
            summary = "میانگین تند از کند رد می‌شود.",
            summaryEn = "The fast EMA crosses the slow one.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("fastLen", 20, "دوره‌ی تند", "Fast length", 2, 400),
                ScriptLibraryInput("slowLen", 50, "دوره‌ی کند", "Slow length", 2, 400),
            ),
            lines = listOf(
                "fast = ta.ema(close, fastLen)",
                "slow = ta.ema(close, slowLen)",
            ),
            plots = listOf(
                ScriptLibraryPlot("fast", "تند", "Fast", "color.gold", "price"),
                ScriptLibraryPlot("slow", "کند", "Slow", "color.blue", "price"),
            ),
            bias = "fast > slow",
            up = "ta.crossover(fast, slow)",
            down = "ta.crossunder(fast, slow)",
            upText = "میانگین تند از کند رد شد",
            upTextEn = "The fast average crossed above the slow one",
            downText = "میانگین تند زیر کند رفت",
            downTextEn = "The fast average crossed below the slow one",
        ),
        ScriptLibraryEntry(
            id = "golden-cross",
            family = ScriptFamily.TREND,
            title = "تقاطع طلایی",
            titleEn = "Golden cross",
            summary = "میانگین ۵۰ از ۲۰۰ رد می‌شود.",
            summaryEn = "The 50 crosses the 200.",
            stopAtr = 3,
            inputs = listOf(
                ScriptLibraryInput("fastLen", 50, "دوره‌ی تند", "Fast length", 2, 400),
                ScriptLibraryInput("slowLen", 200, "دوره‌ی کند", "Slow length", 10, 400),
            ),
            lines = listOf(
                "fast = ta.sma(close, fastLen)",
                "slow = ta.sma(close, slowLen)",
            ),
            plots = listOf(
                ScriptLibraryPlot("fast", "۵۰", "50", "color.gold", "price"),
                ScriptLibraryPlot("slow", "۲۰۰", "200", "color.blue", "price"),
            ),
            bias = "fast > slow",
            up = "ta.crossover(fast, slow)",
            down = "ta.crossunder(fast, slow)",
            upText = "تقاطع طلایی",
            upTextEn = "A golden cross",
            downText = "تقاطع مرگ",
            downTextEn = "A death cross",
        ),
        ScriptLibraryEntry(
            id = "supertrend-flip",
            family = ScriptFamily.TREND,
            title = "چرخش سوپرترند",
            titleEn = "SuperTrend turns",
            summary = "سوپرترند سمتش را عوض می‌کند.",
            summaryEn = "SuperTrend changes side.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 10, "دوره", "Length", 2, 100),
                ScriptLibraryInput("factor", 3, "ضریب", "Factor", 1, 10),
            ),
            lines = listOf(
                "band = ta.supertrend(span, factor)",
                "side = ta.supertrend_trend(span, factor)",
            ),
            plots = listOf(
                ScriptLibraryPlot("band", "سوپرترند", "SuperTrend", "color.gold", "price"),
            ),
            bias = "side > 0",
            up = "ta.crossover(side, 0)",
            down = "ta.crossunder(side, 0)",
            upText = "سوپرترند صعودی شد",
            upTextEn = "SuperTrend turned up",
            downText = "سوپرترند نزولی شد",
            downTextEn = "SuperTrend turned down",
        ),
        ScriptLibraryEntry(
            id = "adx-direction",
            family = ScriptFamily.TREND,
            title = "جهت با قدرت روند",
            titleEn = "Direction with trend strength",
            summary = "خطوط جهت‌دار وقتی ADX بالای آستانه است رد می‌شوند.",
            summaryEn = "The directional lines cross while ADX is over its gate.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 100),
                ScriptLibraryInput("gate", 25, "آستانه", "Gate", 5, 60),
            ),
            lines = listOf(
                "plus = ta.di_plus(span)",
                "minus = ta.di_minus(span)",
                "strength = ta.adx(span)",
                "strong = strength > gate",
            ),
            plots = listOf(
                ScriptLibraryPlot("plus", "جهت مثبت", "DI+", "color.buy", "own"),
                ScriptLibraryPlot("minus", "جهت منفی", "DI−", "color.sell", "own"),
                ScriptLibraryPlot("strength", "ADX", "ADX", "color.gold", "own"),
            ),
            bias = "plus > minus",
            up = "ta.crossover(plus, minus) and strong",
            down = "ta.crossunder(plus, minus) and strong",
            upText = "جهت مثبت با روند قوی",
            upTextEn = "The positive line took over in a strong trend",
            downText = "جهت منفی با روند قوی",
            downTextEn = "The negative line took over in a strong trend",
        ),
        ScriptLibraryEntry(
            id = "psar-flip",
            family = ScriptFamily.TREND,
            title = "چرخش پارابولیک",
            titleEn = "Parabolic SAR flips",
            summary = "قیمت از نقطه‌های پارابولیک رد می‌شود.",
            summaryEn = "Price crosses the parabolic dots.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("step", 2, "گام (صدم)", "Step (hundredths)", 1, 20),
                ScriptLibraryInput("cap", 20, "سقف (صدم)", "Cap (hundredths)", 5, 50),
            ),
            lines = listOf(
                "dots = ta.psar(step / 100, cap / 100)",
            ),
            plots = listOf(
                ScriptLibraryPlot("dots", "پارابولیک", "SAR", "color.grey", "price"),
            ),
            bias = "close > dots",
            up = "ta.crossover(close, dots)",
            down = "ta.crossunder(close, dots)",
            upText = "قیمت بالای پارابولیک رفت",
            upTextEn = "Price went over the SAR",
            downText = "قیمت زیر پارابولیک رفت",
            downTextEn = "Price went under the SAR",
        ),
        ScriptLibraryEntry(
            id = "ichimoku-base",
            family = ScriptFamily.TREND,
            title = "تقاطع تنکان و کیجون",
            titleEn = "Tenkan crosses Kijun",
            summary = "خط تبدیل از خط پایه رد می‌شود.",
            summaryEn = "The conversion line crosses the base line.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("fastLen", 9, "تنکان", "Tenkan", 2, 100),
                ScriptLibraryInput("slowLen", 26, "کیجون", "Kijun", 2, 200),
            ),
            lines = listOf(
                "conversion = ta.ichimoku_conversion(fastLen, slowLen)",
                "baseLine = ta.ichimoku_base(fastLen, slowLen)",
            ),
            plots = listOf(
                ScriptLibraryPlot("conversion", "تنکان", "Tenkan", "color.gold", "price"),
                ScriptLibraryPlot("baseLine", "کیجون", "Kijun", "color.blue", "price"),
            ),
            bias = "conversion > baseLine",
            up = "ta.crossover(conversion, baseLine)",
            down = "ta.crossunder(conversion, baseLine)",
            upText = "تنکان از کیجون رد شد",
            upTextEn = "Tenkan crossed above Kijun",
            downText = "تنکان زیر کیجون رفت",
            downTextEn = "Tenkan crossed below Kijun",
        ),
        ScriptLibraryEntry(
            id = "hma-slope",
            family = ScriptFamily.TREND,
            title = "شیب میانگین هال",
            titleEn = "The Hull average turns",
            summary = "میانگین هال چند کندل پشت سر هم بالا یا پایین می‌رود.",
            summaryEn = "The Hull average rises or falls several bars running.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 21, "دوره", "Length", 2, 200),
                ScriptLibraryInput("bars", 3, "تعداد کندل", "Bars", 2, 10),
            ),
            lines = listOf(
                "hull = ta.hma(close, span)",
                "climbing = ta.rising(hull, bars)",
                "sinking = ta.falling(hull, bars)",
            ),
            plots = listOf(
                ScriptLibraryPlot("hull", "هال", "Hull", "color.gold", "price"),
            ),
            bias = "climbing",
            up = "climbing and not climbing[1]",
            down = "sinking and not sinking[1]",
            upText = "میانگین هال شروع به بالا رفتن کرد",
            upTextEn = "The Hull average started climbing",
            downText = "میانگین هال شروع به پایین آمدن کرد",
            downTextEn = "The Hull average started sinking",
        ),
        ScriptLibraryEntry(
            id = "kama-trend",
            family = ScriptFamily.TREND,
            title = "میانگین تطبیقی کافمن",
            titleEn = "Kaufman's adaptive average",
            summary = "قیمت از میانگینی که با سرعت بازار تنظیم می‌شود رد می‌شود.",
            summaryEn = "Price crosses an average that adapts to the market's speed.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 10, "دوره", "Length", 2, 100),
            ),
            lines = listOf(
                "adaptive = ta.kama(close, span, 2, 30)",
            ),
            plots = listOf(
                ScriptLibraryPlot("adaptive", "کافمن", "KAMA", "color.gold", "price"),
            ),
            bias = "close > adaptive",
            up = "ta.crossover(close, adaptive)",
            down = "ta.crossunder(close, adaptive)",
            upText = "قیمت بالای میانگین تطبیقی رفت",
            upTextEn = "Price went over the adaptive average",
            downText = "قیمت زیر میانگین تطبیقی رفت",
            downTextEn = "Price went under the adaptive average",
        ),
        ScriptLibraryEntry(
            id = "linreg-turn",
            family = ScriptFamily.TREND,
            title = "چرخش خط رگرسیون",
            titleEn = "The regression line turns",
            summary = "شیب خط رگرسیون علامتش را عوض می‌کند.",
            summaryEn = "The regression line's slope changes sign.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 3, 200),
            ),
            lines = listOf(
                "fit = ta.linreg(close, span)",
                "slope = ta.change(fit, 1)",
            ),
            plots = listOf(
                ScriptLibraryPlot("fit", "رگرسیون", "Regression", "color.gold", "price"),
            ),
            bias = "slope > 0",
            up = "ta.crossover(slope, 0)",
            down = "ta.crossunder(slope, 0)",
            upText = "خط رگرسیون رو به بالا چرخید",
            upTextEn = "The regression line turned up",
            downText = "خط رگرسیون رو به پایین چرخید",
            downTextEn = "The regression line turned down",
        ),
        ScriptLibraryEntry(
            id = "alligator",
            family = ScriptFamily.TREND,
            title = "تمساح ویلیامز",
            titleEn = "Williams' Alligator",
            summary = "لب‌ها از دندان‌ها رد می‌شوند.",
            summaryEn = "The lips cross the teeth.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "lips = ta.alligator_lips()",
                "teeth = ta.alligator_teeth()",
                "jaw = ta.alligator_jaw()",
            ),
            plots = listOf(
                ScriptLibraryPlot("lips", "لب", "Lips", "color.buy", "price"),
                ScriptLibraryPlot("teeth", "دندان", "Teeth", "color.gold", "price"),
                ScriptLibraryPlot("jaw", "فک", "Jaw", "color.blue", "price"),
            ),
            bias = "lips > teeth",
            up = "ta.crossover(lips, teeth)",
            down = "ta.crossunder(lips, teeth)",
            upText = "تمساح دهانش را باز کرد",
            upTextEn = "The alligator opened its mouth",
            downText = "تمساح رو به پایین باز شد",
            downTextEn = "The alligator opened downwards",
        ),
        ScriptLibraryEntry(
            id = "vortex",
            family = ScriptFamily.TREND,
            title = "تقاطع ورتکس",
            titleEn = "The Vortex lines cross",
            summary = "خط مثبت ورتکس از خط منفی رد می‌شود.",
            summaryEn = "The positive Vortex line crosses the negative one.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 100),
            ),
            lines = listOf(
                "plusLine = ta.vortex_plus(span)",
                "minusLine = ta.vortex_minus(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("plusLine", "ورتکس مثبت", "VI+", "color.buy", "own"),
                ScriptLibraryPlot("minusLine", "ورتکس منفی", "VI−", "color.sell", "own"),
            ),
            bias = "plusLine > minusLine",
            up = "ta.crossover(plusLine, minusLine)",
            down = "ta.crossunder(plusLine, minusLine)",
            upText = "ورتکس مثبت جلو افتاد",
            upTextEn = "The positive Vortex line took over",
            downText = "ورتکس منفی جلو افتاد",
            downTextEn = "The negative Vortex line took over",
        ),
        ScriptLibraryEntry(
            id = "ma-ribbon",
            family = ScriptFamily.TREND,
            title = "چیده شدن سه میانگین",
            titleEn = "Three averages line up",
            summary = "سه میانگین نمایی پشت سر هم مرتب می‌شوند.",
            summaryEn = "Three EMAs stack in order.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("oneLen", 10, "دوره‌ی اول", "First length", 2, 100),
                ScriptLibraryInput("twoLen", 20, "دوره‌ی دوم", "Second length", 2, 200),
                ScriptLibraryInput("threeLen", 50, "دوره‌ی سوم", "Third length", 2, 400),
            ),
            lines = listOf(
                "one = ta.ema(close, oneLen)",
                "two = ta.ema(close, twoLen)",
                "three = ta.ema(close, threeLen)",
                "stackedUp = one > two and two > three",
                "stackedDown = one < two and two < three",
            ),
            plots = listOf(
                ScriptLibraryPlot("one", "اول", "First", "color.buy", "price"),
                ScriptLibraryPlot("two", "دوم", "Second", "color.gold", "price"),
                ScriptLibraryPlot("three", "سوم", "Third", "color.blue", "price"),
            ),
            bias = "stackedUp",
            up = "stackedUp and not stackedUp[1]",
            down = "stackedDown and not stackedDown[1]",
            upText = "هر سه میانگین صعودی چیده شدند",
            upTextEn = "All three averages stacked upwards",
            downText = "هر سه میانگین نزولی چیده شدند",
            downTextEn = "All three averages stacked downwards",
        ),
        ScriptLibraryEntry(
            id = "rsi-midline",
            family = ScriptFamily.MOMENTUM,
            title = "عبور RSI از میانه",
            titleEn = "RSI crosses its middle",
            summary = "RSI از خط ۵۰ رد می‌شود.",
            summaryEn = "RSI crosses the fifty line.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 200),
            ),
            lines = listOf(
                "r = ta.rsi(close, span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("r", "RSI", "RSI", "color.gold", "own"),
            ),
            bias = "r > 50",
            up = "ta.crossover(r, 50)",
            down = "ta.crossunder(r, 50)",
            upText = "RSI از میانه بالا رفت",
            upTextEn = "RSI went over the middle",
            downText = "RSI از میانه پایین آمد",
            downTextEn = "RSI went under the middle",
        ),
        ScriptLibraryEntry(
            id = "macd-cross",
            family = ScriptFamily.MOMENTUM,
            title = "تقاطع مکدی",
            titleEn = "MACD crosses its signal",
            summary = "مکدی از خط سیگنالش رد می‌شود.",
            summaryEn = "MACD crosses its signal line.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("fastLen", 12, "تند", "Fast", 2, 200),
                ScriptLibraryInput("slowLen", 26, "کند", "Slow", 2, 400),
                ScriptLibraryInput("signalLen", 9, "سیگنال", "Signal", 1, 100),
            ),
            lines = listOf(
                "macdLine = ta.macd(close, fastLen, slowLen, signalLen)",
                "signalLine = ta.macd_signal(close, fastLen, slowLen, signalLen)",
            ),
            plots = listOf(
                ScriptLibraryPlot("macdLine", "مکدی", "MACD", "color.gold", "own"),
                ScriptLibraryPlot("signalLine", "سیگنال", "Signal", "color.blue", "own"),
            ),
            bias = "macdLine > signalLine",
            up = "ta.crossover(macdLine, signalLine)",
            down = "ta.crossunder(macdLine, signalLine)",
            upText = "مکدی از سیگنالش رد شد",
            upTextEn = "MACD crossed above its signal",
            downText = "مکدی زیر سیگنالش رفت",
            downTextEn = "MACD crossed below its signal",
        ),
        ScriptLibraryEntry(
            id = "macd-zero",
            family = ScriptFamily.MOMENTUM,
            title = "عبور مکدی از صفر",
            titleEn = "MACD crosses zero",
            summary = "مکدی علامتش را عوض می‌کند.",
            summaryEn = "MACD changes sign.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("fastLen", 12, "تند", "Fast", 2, 200),
                ScriptLibraryInput("slowLen", 26, "کند", "Slow", 2, 400),
            ),
            lines = listOf(
                "macdLine = ta.macd(close, fastLen, slowLen, 9)",
            ),
            plots = listOf(
                ScriptLibraryPlot("macdLine", "مکدی", "MACD", "color.gold", "own"),
            ),
            bias = "macdLine > 0",
            up = "ta.crossover(macdLine, 0)",
            down = "ta.crossunder(macdLine, 0)",
            upText = "مکدی مثبت شد",
            upTextEn = "MACD turned positive",
            downText = "مکدی منفی شد",
            downTextEn = "MACD turned negative",
        ),
        ScriptLibraryEntry(
            id = "stoch-cross",
            family = ScriptFamily.MOMENTUM,
            title = "تقاطع استوکاستیک",
            titleEn = "The stochastic lines cross",
            summary = "خط K از خط D رد می‌شود.",
            summaryEn = "The %K line crosses %D.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 100),
                ScriptLibraryInput("smoothing", 3, "هموارسازی", "Smoothing", 1, 20),
            ),
            lines = listOf(
                "kLine = ta.stoch_k(span, smoothing)",
                "dLine = ta.stoch_d(span, smoothing)",
            ),
            plots = listOf(
                ScriptLibraryPlot("kLine", "K", "%K", "color.gold", "own"),
                ScriptLibraryPlot("dLine", "D", "%D", "color.blue", "own"),
            ),
            bias = "kLine > dLine",
            up = "ta.crossover(kLine, dLine)",
            down = "ta.crossunder(kLine, dLine)",
            upText = "K از D رد شد",
            upTextEn = "%K crossed above %D",
            downText = "K زیر D رفت",
            downTextEn = "%K crossed below %D",
        ),
        ScriptLibraryEntry(
            id = "cci-zero",
            family = ScriptFamily.MOMENTUM,
            title = "عبور CCI از صفر",
            titleEn = "CCI crosses zero",
            summary = "شاخص کانال کالا علامتش را عوض می‌کند.",
            summaryEn = "The commodity channel index changes sign.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
            ),
            lines = listOf(
                "channel = ta.cci(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("channel", "CCI", "CCI", "color.gold", "own"),
            ),
            bias = "channel > 0",
            up = "ta.crossover(channel, 0)",
            down = "ta.crossunder(channel, 0)",
            upText = "CCI مثبت شد",
            upTextEn = "CCI turned positive",
            downText = "CCI منفی شد",
            downTextEn = "CCI turned negative",
        ),
        ScriptLibraryEntry(
            id = "momentum-zero",
            family = ScriptFamily.MOMENTUM,
            title = "چرخش مومنتوم",
            titleEn = "Momentum turns",
            summary = "اختلاف قیمت با n کندل قبل علامتش را عوض می‌کند.",
            summaryEn = "The distance from n bars ago changes sign.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 10, "دوره", "Length", 1, 200),
            ),
            lines = listOf(
                "push = ta.momentum(close, span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("push", "مومنتوم", "Momentum", "color.gold", "own"),
            ),
            bias = "push > 0",
            up = "ta.crossover(push, 0)",
            down = "ta.crossunder(push, 0)",
            upText = "مومنتوم مثبت شد",
            upTextEn = "Momentum turned positive",
            downText = "مومنتوم منفی شد",
            downTextEn = "Momentum turned negative",
        ),
        ScriptLibraryEntry(
            id = "trix-signal",
            family = ScriptFamily.MOMENTUM,
            title = "تقاطع TRIX",
            titleEn = "TRIX crosses its signal",
            summary = "TRIX از خط سیگنالش رد می‌شود.",
            summaryEn = "TRIX crosses its signal line.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 18, "دوره", "Length", 2, 200),
                ScriptLibraryInput("signalLen", 9, "سیگنال", "Signal", 1, 100),
            ),
            lines = listOf(
                "trixLine = ta.trix(close, span, signalLen)",
                "signalLine = ta.trix_signal(close, span, signalLen)",
            ),
            plots = listOf(
                ScriptLibraryPlot("trixLine", "TRIX", "TRIX", "color.gold", "own"),
                ScriptLibraryPlot("signalLine", "سیگنال", "Signal", "color.blue", "own"),
            ),
            bias = "trixLine > signalLine",
            up = "ta.crossover(trixLine, signalLine)",
            down = "ta.crossunder(trixLine, signalLine)",
            upText = "TRIX از سیگنالش رد شد",
            upTextEn = "TRIX crossed above its signal",
            downText = "TRIX زیر سیگنالش رفت",
            downTextEn = "TRIX crossed below its signal",
        ),
        ScriptLibraryEntry(
            id = "tsi-signal",
            family = ScriptFamily.MOMENTUM,
            title = "تقاطع TSI",
            titleEn = "TSI crosses its signal",
            summary = "شاخص قدرت واقعی از سیگنالش رد می‌شود.",
            summaryEn = "The true strength index crosses its signal.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("longLen", 25, "دوره‌ی بلند", "Long length", 2, 200),
                ScriptLibraryInput("shortLen", 13, "دوره‌ی کوتاه", "Short length", 2, 100),
            ),
            lines = listOf(
                "tsiLine = ta.tsi(close, longLen, shortLen, 13)",
                "signalLine = ta.tsi_signal(close, longLen, shortLen, 13)",
            ),
            plots = listOf(
                ScriptLibraryPlot("tsiLine", "TSI", "TSI", "color.gold", "own"),
                ScriptLibraryPlot("signalLine", "سیگنال", "Signal", "color.blue", "own"),
            ),
            bias = "tsiLine > signalLine",
            up = "ta.crossover(tsiLine, signalLine)",
            down = "ta.crossunder(tsiLine, signalLine)",
            upText = "TSI از سیگنالش رد شد",
            upTextEn = "TSI crossed above its signal",
            downText = "TSI زیر سیگنالش رفت",
            downTextEn = "TSI crossed below its signal",
        ),
        ScriptLibraryEntry(
            id = "ao-zero",
            family = ScriptFamily.MOMENTUM,
            title = "عبور اوسم از صفر",
            titleEn = "The Awesome Oscillator crosses zero",
            summary = "اوسیلاتور عالی علامتش را عوض می‌کند.",
            summaryEn = "The Awesome Oscillator changes sign.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "wave = ta.ao()",
            ),
            plots = listOf(
                ScriptLibraryPlot("wave", "AO", "AO", "color.gold", "own"),
            ),
            bias = "wave > 0",
            up = "ta.crossover(wave, 0)",
            down = "ta.crossunder(wave, 0)",
            upText = "اوسم مثبت شد",
            upTextEn = "The oscillator turned positive",
            downText = "اوسم منفی شد",
            downTextEn = "The oscillator turned negative",
        ),
        ScriptLibraryEntry(
            id = "cmo-zero",
            family = ScriptFamily.MOMENTUM,
            title = "چرخش CMO",
            titleEn = "CMO turns",
            summary = "اوسیلاتور مومنتوم چاند علامتش را عوض می‌کند.",
            summaryEn = "Chande's momentum oscillator changes sign.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 9, "دوره", "Length", 2, 100),
            ),
            lines = listOf(
                "swing = ta.cmo(close, span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("swing", "CMO", "CMO", "color.gold", "own"),
            ),
            bias = "swing > 0",
            up = "ta.crossover(swing, 0)",
            down = "ta.crossunder(swing, 0)",
            upText = "CMO مثبت شد",
            upTextEn = "CMO turned positive",
            downText = "CMO منفی شد",
            downTextEn = "CMO turned negative",
        ),
        ScriptLibraryEntry(
            id = "williams-turn",
            family = ScriptFamily.MOMENTUM,
            title = "بازگشت ویلیامز",
            titleEn = "Williams %R comes back",
            summary = "ویلیامز از کف یا سقفش برمی‌گردد.",
            summaryEn = "Williams %R comes back over its floor or under its ceiling.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 100),
            ),
            lines = listOf(
                "reading = ta.williams_r(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("reading", "ویلیامز", "%R", "color.gold", "own"),
            ),
            bias = "reading > -50",
            up = "ta.crossover(reading, -80)",
            down = "ta.crossunder(reading, -20)",
            upText = "ویلیامز از کف برگشت",
            upTextEn = "%R came back over its floor",
            downText = "ویلیامز از سقف پایین آمد",
            downTextEn = "%R came back under its ceiling",
        ),
        ScriptLibraryEntry(
            id = "roc-zero",
            family = ScriptFamily.MOMENTUM,
            title = "چرخش نرخ تغییر",
            titleEn = "The rate of change turns",
            summary = "درصد تغییر نسبت به n کندل قبل علامتش را عوض می‌کند.",
            summaryEn = "The percent change from n bars ago changes sign.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 12, "دوره", "Length", 1, 200),
            ),
            lines = listOf(
                "pace = ta.roc(close, span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("pace", "نرخ تغییر", "ROC", "color.gold", "own"),
            ),
            bias = "pace > 0",
            up = "ta.crossover(pace, 0)",
            down = "ta.crossunder(pace, 0)",
            upText = "نرخ تغییر مثبت شد",
            upTextEn = "The rate of change turned positive",
            downText = "نرخ تغییر منفی شد",
            downTextEn = "The rate of change turned negative",
        ),
        ScriptLibraryEntry(
            id = "kst-signal",
            family = ScriptFamily.MOMENTUM,
            title = "تقاطع KST",
            titleEn = "KST crosses its signal",
            summary = "شاخص «مطمئن باش» از سیگنالش رد می‌شود.",
            summaryEn = "Know Sure Thing crosses its signal.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "kstLine = ta.kst(close)",
                "signalLine = ta.kst_signal(close)",
            ),
            plots = listOf(
                ScriptLibraryPlot("kstLine", "KST", "KST", "color.gold", "own"),
                ScriptLibraryPlot("signalLine", "سیگنال", "Signal", "color.blue", "own"),
            ),
            bias = "kstLine > signalLine",
            up = "ta.crossover(kstLine, signalLine)",
            down = "ta.crossunder(kstLine, signalLine)",
            upText = "KST از سیگنالش رد شد",
            upTextEn = "KST crossed above its signal",
            downText = "KST زیر سیگنالش رفت",
            downTextEn = "KST crossed below its signal",
        ),
        ScriptLibraryEntry(
            id = "donchian-break",
            family = ScriptFamily.BREAKOUT,
            title = "شکست کانال دانچیان",
            titleEn = "Breaking the Donchian channel",
            summary = "قیمت از سقف یا کف n کندل قبل رد می‌شود.",
            summaryEn = "Price passes the highest or lowest of the last n bars.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 400),
            ),
            lines = listOf(
                "top = ta.donchian_upper(span)[1]",
                "bottom = ta.donchian_lower(span)[1]",
            ),
            plots = listOf(
                ScriptLibraryPlot("top", "سقف", "Top", "color.buy", "price"),
                ScriptLibraryPlot("bottom", "کف", "Bottom", "color.sell", "price"),
            ),
            bias = "close > top",
            up = "close > top",
            down = "close < bottom",
            upText = "سقف کانال شکست",
            upTextEn = "The channel's top broke",
            downText = "کف کانال شکست",
            downTextEn = "The channel's bottom broke",
        ),
        ScriptLibraryEntry(
            id = "squeeze-break",
            family = ScriptFamily.BREAKOUT,
            title = "شکست بعد از فشردگی",
            titleEn = "A break after a squeeze",
            summary = "باند بولینگر تنگ می‌شود و بعد قیمت از آن بیرون می‌زند.",
            summaryEn = "The Bollinger bands tighten, then price leaves them.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
                ScriptLibraryInput("width", 2, "انحراف", "Deviation", 1, 5),
            ),
            lines = listOf(
                "upper = ta.bb_upper(close, span, width)",
                "lower = ta.bb_lower(close, span, width)",
                "tightness = ta.bb_width(close, span, width)",
                "squeezed = tightness < ta.lowest(tightness, span)[1] * 1.1",
            ),
            plots = listOf(
                ScriptLibraryPlot("upper", "بالا", "Upper", "color.sell", "price"),
                ScriptLibraryPlot("lower", "پایین", "Lower", "color.buy", "price"),
            ),
            bias = "close > upper",
            up = "squeezed[1] and close > upper",
            down = "squeezed[1] and close < lower",
            upText = "بعد از فشردگی رو به بالا شکست",
            upTextEn = "It broke upwards out of a squeeze",
            downText = "بعد از فشردگی رو به پایین شکست",
            downTextEn = "It broke downwards out of a squeeze",
        ),
        ScriptLibraryEntry(
            id = "keltner-break",
            family = ScriptFamily.BREAKOUT,
            title = "شکست کانال کلتنر",
            titleEn = "Breaking the Keltner channel",
            summary = "قیمت از کانالی به اندازه‌ی چند ATR بیرون می‌زند.",
            summaryEn = "Price leaves a channel a few ATRs wide.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
                ScriptLibraryInput("factor", 2, "ضریب", "Factor", 1, 6),
            ),
            lines = listOf(
                "upper = ta.keltner_upper(span, factor)",
                "lower = ta.keltner_lower(span, factor)",
            ),
            plots = listOf(
                ScriptLibraryPlot("upper", "بالا", "Upper", "color.sell", "price"),
                ScriptLibraryPlot("lower", "پایین", "Lower", "color.buy", "price"),
            ),
            bias = "close > upper",
            up = "ta.crossover(close, upper)",
            down = "ta.crossunder(close, lower)",
            upText = "از کلتنر بالا زد",
            upTextEn = "It broke over the Keltner channel",
            downText = "از کلتنر پایین زد",
            downTextEn = "It broke under the Keltner channel",
        ),
        ScriptLibraryEntry(
            id = "n-bar-high",
            family = ScriptFamily.BREAKOUT,
            title = "بالاترین n کندل",
            titleEn = "The highest of n bars",
            summary = "قیمت بالاتر از سقف n کندل گذشته بسته می‌شود.",
            summaryEn = "Price closes above the highest of the last n bars.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 55, "دوره", "Length", 2, 400),
            ),
            lines = listOf(
                "top = ta.highest(high, span)[1]",
                "bottom = ta.lowest(low, span)[1]",
            ),
            plots = listOf(
                ScriptLibraryPlot("top", "سقف", "Top", "color.buy", "price"),
                ScriptLibraryPlot("bottom", "کف", "Bottom", "color.sell", "price"),
            ),
            bias = "close > top",
            up = "close > top",
            down = "close < bottom",
            upText = "بالاترین قیمت دوره",
            upTextEn = "The highest of the period",
            downText = "پایین‌ترین قیمت دوره",
            downTextEn = "The lowest of the period",
        ),
        ScriptLibraryEntry(
            id = "inside-bar-break",
            family = ScriptFamily.BREAKOUT,
            title = "شکست کندل داخلی",
            titleEn = "An inside bar breaks",
            summary = "کندلی که داخل کندل قبلش بود شکسته می‌شود.",
            summaryEn = "A bar that sat inside the one before it is broken.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "inside = high[1] < high[2] and low[1] > low[2]",
            ),
            plots = emptyList(),
            bias = "close > high[1]",
            up = "inside and close > high[1]",
            down = "inside and close < low[1]",
            upText = "کندل داخلی رو به بالا شکست",
            upTextEn = "The inside bar broke upwards",
            downText = "کندل داخلی رو به پایین شکست",
            downTextEn = "The inside bar broke downwards",
        ),
        ScriptLibraryEntry(
            id = "opening-range",
            family = ScriptFamily.BREAKOUT,
            title = "شکست محدوده‌ی مرجع",
            titleEn = "Breaking a reference range",
            summary = "قیمت از سقف یا کف کندل مرجع رد می‌شود.",
            summaryEn = "Price passes the reference bar's high or low.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("back", 1, "کندل مرجع", "Reference bar", 1, 50),
            ),
            lines = listOf(
                "top = high[back]",
                "bottom = low[back]",
            ),
            plots = listOf(
                ScriptLibraryPlot("top", "سقف مرجع", "Reference high", "color.buy", "price"),
                ScriptLibraryPlot("bottom", "کف مرجع", "Reference low", "color.sell", "price"),
            ),
            bias = "close > top",
            up = "ta.crossover(close, top)",
            down = "ta.crossunder(close, bottom)",
            upText = "سقف مرجع شکست",
            upTextEn = "The reference high broke",
            downText = "کف مرجع شکست",
            downTextEn = "The reference low broke",
        ),
        ScriptLibraryEntry(
            id = "range-expansion",
            family = ScriptFamily.BREAKOUT,
            title = "باز شدن دامنه",
            titleEn = "The range opens up",
            summary = "دامنه‌ی کندل چند برابر میانگینش می‌شود.",
            summaryEn = "The bar's range grows to a multiple of its own average.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 200),
                ScriptLibraryInput("times", 2, "چند برابر", "Multiple", 1, 8),
            ),
            lines = listOf(
                "reach = ta.tr()",
                "usual = ta.atr(span)",
                "wide = reach > usual * times",
            ),
            plots = listOf(
                ScriptLibraryPlot("usual", "ATR", "ATR", "color.grey", "own"),
                ScriptLibraryPlot("reach", "دامنه", "Range", "color.gold", "own"),
            ),
            bias = "close > open",
            up = "wide and close > open",
            down = "wide and close < open",
            upText = "کندل بزرگ صعودی",
            upTextEn = "A big rising bar",
            downText = "کندل بزرگ نزولی",
            downTextEn = "A big falling bar",
        ),
        ScriptLibraryEntry(
            id = "pivot-break",
            family = ScriptFamily.BREAKOUT,
            title = "شکست پیوت",
            titleEn = "A pivot breaks",
            summary = "قیمت از آخرین سقف یا کف محلی رد می‌شود.",
            summaryEn = "Price passes the last local high or low.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("wing", 5, "بال پیوت", "Pivot wing", 1, 30),
            ),
            lines = listOf(
                "topPivot = ta.valuewhen(not na(ta.pivothigh(wing, wing)), high[wing], 0)",
                "bottomPivot = ta.valuewhen(not na(ta.pivotlow(wing, wing)), low[wing], 0)",
            ),
            plots = listOf(
                ScriptLibraryPlot("topPivot", "پیوت سقف", "Pivot high", "color.sell", "price"),
                ScriptLibraryPlot("bottomPivot", "پیوت کف", "Pivot low", "color.buy", "price"),
            ),
            bias = "close > topPivot",
            up = "ta.crossover(close, topPivot)",
            down = "ta.crossunder(close, bottomPivot)",
            upText = "پیوت سقف شکست",
            upTextEn = "The pivot high broke",
            downText = "پیوت کف شکست",
            downTextEn = "The pivot low broke",
        ),
        ScriptLibraryEntry(
            id = "rsi-extremes",
            family = ScriptFamily.REVERSION,
            title = "بازگشت RSI از اشباع",
            titleEn = "RSI comes back from an extreme",
            summary = "RSI از کف برمی‌گردد یا از سقف پایین می‌آید.",
            summaryEn = "RSI comes back over its floor or under its ceiling.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 200),
                ScriptLibraryInput("floorLevel", 30, "کف", "Floor", 1, 49),
                ScriptLibraryInput("ceilingLevel", 70, "سقف", "Ceiling", 51, 99),
            ),
            lines = listOf(
                "r = ta.rsi(close, span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("r", "RSI", "RSI", "color.gold", "own"),
            ),
            bias = "r < 50",
            up = "ta.crossover(r, floorLevel)",
            down = "ta.crossunder(r, ceilingLevel)",
            upText = "RSI از کف برگشت",
            upTextEn = "RSI came back over its floor",
            downText = "RSI از سقف پایین آمد",
            downTextEn = "RSI came back under its ceiling",
        ),
        ScriptLibraryEntry(
            id = "bollinger-touch",
            family = ScriptFamily.REVERSION,
            title = "برگشت از باند بولینگر",
            titleEn = "Coming back off a Bollinger band",
            summary = "قیمت از باند بیرونی به داخل برمی‌گردد.",
            summaryEn = "Price comes back inside the outer band.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
                ScriptLibraryInput("width", 2, "انحراف", "Deviation", 1, 5),
            ),
            lines = listOf(
                "mid = ta.bb_basis(close, span, width)",
                "upper = ta.bb_upper(close, span, width)",
                "lower = ta.bb_lower(close, span, width)",
            ),
            plots = listOf(
                ScriptLibraryPlot("mid", "میانه", "Middle", "color.gold", "price"),
                ScriptLibraryPlot("upper", "بالا", "Upper", "color.sell", "price"),
                ScriptLibraryPlot("lower", "پایین", "Lower", "color.buy", "price"),
            ),
            bias = "close < mid",
            up = "ta.crossover(close, lower)",
            down = "ta.crossunder(close, upper)",
            upText = "از باند پایین برگشت",
            upTextEn = "It came back off the lower band",
            downText = "از باند بالا برگشت",
            downTextEn = "It came back off the upper band",
        ),
        ScriptLibraryEntry(
            id = "stochrsi-extremes",
            family = ScriptFamily.REVERSION,
            title = "بازگشت استوکاستیک RSI",
            titleEn = "Stochastic RSI comes back",
            summary = "استوکاستیک RSI از کف یا سقفش برمی‌گردد.",
            summaryEn = "Stochastic RSI comes back from its floor or ceiling.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 100),
            ),
            lines = listOf(
                "kLine = ta.stochrsi_k(close, span, span, 3, 3)",
            ),
            plots = listOf(
                ScriptLibraryPlot("kLine", "K", "%K", "color.gold", "own"),
            ),
            bias = "kLine < 50",
            up = "ta.crossover(kLine, 20)",
            down = "ta.crossunder(kLine, 80)",
            upText = "استوکاستیک RSI از کف برگشت",
            upTextEn = "Stochastic RSI came back over its floor",
            downText = "استوکاستیک RSI از سقف پایین آمد",
            downTextEn = "Stochastic RSI came back under its ceiling",
        ),
        ScriptLibraryEntry(
            id = "zscore",
            family = ScriptFamily.REVERSION,
            title = "فاصله از میانگین",
            titleEn = "Distance from the average",
            summary = "قیمت چند انحراف معیار از میانگینش دور می‌شود و برمی‌گردد.",
            summaryEn = "Price goes a few deviations from its average and comes back.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 3, 200),
                ScriptLibraryInput("edge", 2, "آستانه", "Threshold", 1, 5),
            ),
            lines = listOf(
                "mid = ta.sma(close, span)",
                "spread = ta.stdev(close, span)",
                "distance = (close - mid) / spread",
            ),
            plots = listOf(
                ScriptLibraryPlot("distance", "فاصله", "Distance", "color.gold", "own"),
            ),
            bias = "distance < 0",
            up = "ta.crossover(distance, 0 - edge)",
            down = "ta.crossunder(distance, edge)",
            upText = "از فاصله‌ی زیاد پایین برگشت",
            upTextEn = "It came back from far below",
            downText = "از فاصله‌ی زیاد بالا برگشت",
            downTextEn = "It came back from far above",
        ),
        ScriptLibraryEntry(
            id = "cci-extremes",
            family = ScriptFamily.REVERSION,
            title = "بازگشت CCI",
            titleEn = "CCI comes back",
            summary = "CCI از ±۱۰۰ برمی‌گردد.",
            summaryEn = "CCI comes back from ±100.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
            ),
            lines = listOf(
                "channel = ta.cci(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("channel", "CCI", "CCI", "color.gold", "own"),
            ),
            bias = "channel < 0",
            up = "ta.crossover(channel, -100)",
            down = "ta.crossunder(channel, 100)",
            upText = "CCI از کف برگشت",
            upTextEn = "CCI came back over its floor",
            downText = "CCI از سقف پایین آمد",
            downTextEn = "CCI came back under its ceiling",
        ),
        ScriptLibraryEntry(
            id = "envelope-touch",
            family = ScriptFamily.REVERSION,
            title = "برگشت از پاکت",
            titleEn = "Coming back off the envelope",
            summary = "قیمت از پاکت درصدی برمی‌گردد.",
            summaryEn = "Price comes back off a percentage envelope.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
                ScriptLibraryInput("size", 1, "درصد", "Percent", 1, 20),
            ),
            lines = listOf(
                "upper = ta.env_upper(close, span, size)",
                "lower = ta.env_lower(close, span, size)",
                "mid = ta.env_basis(close, span, size)",
            ),
            plots = listOf(
                ScriptLibraryPlot("upper", "بالا", "Upper", "color.sell", "price"),
                ScriptLibraryPlot("lower", "پایین", "Lower", "color.buy", "price"),
                ScriptLibraryPlot("mid", "میانه", "Middle", "color.gold", "price"),
            ),
            bias = "close < mid",
            up = "ta.crossover(close, lower)",
            down = "ta.crossunder(close, upper)",
            upText = "از پاکت پایین برگشت",
            upTextEn = "It came back off the lower envelope",
            downText = "از پاکت بالا برگشت",
            downTextEn = "It came back off the upper envelope",
        ),
        ScriptLibraryEntry(
            id = "dpo-extremes",
            family = ScriptFamily.REVERSION,
            title = "بازگشت DPO",
            titleEn = "The detrended oscillator comes back",
            summary = "اوسیلاتور بدون روند از دو سرش برمی‌گردد.",
            summaryEn = "The detrended price oscillator comes back from either end.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 3, 200),
            ),
            lines = listOf(
                "detrended = ta.dpo(close, span)",
                "spread = ta.stdev(detrended, span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("detrended", "DPO", "DPO", "color.gold", "own"),
            ),
            bias = "detrended < 0",
            up = "ta.crossover(detrended, 0 - spread)",
            down = "ta.crossunder(detrended, spread)",
            upText = "DPO از کف برگشت",
            upTextEn = "DPO came back from below",
            downText = "DPO از سقف برگشت",
            downTextEn = "DPO came back from above",
        ),
        ScriptLibraryEntry(
            id = "crsi-extremes",
            family = ScriptFamily.REVERSION,
            title = "بازگشت کانرز RSI",
            titleEn = "Connors RSI comes back",
            summary = "کانرز RSI از کف یا سقفش برمی‌گردد.",
            summaryEn = "Connors RSI comes back from its floor or ceiling.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "reading = ta.crsi(close, 3, 2, 100)",
            ),
            plots = listOf(
                ScriptLibraryPlot("reading", "CRSI", "CRSI", "color.gold", "own"),
            ),
            bias = "reading < 50",
            up = "ta.crossover(reading, 15)",
            down = "ta.crossunder(reading, 85)",
            upText = "کانرز RSI از کف برگشت",
            upTextEn = "Connors RSI came back over its floor",
            downText = "کانرز RSI از سقف پایین آمد",
            downTextEn = "Connors RSI came back under its ceiling",
        ),
        ScriptLibraryEntry(
            id = "bb-percent",
            family = ScriptFamily.REVERSION,
            title = "جای قیمت در باند",
            titleEn = "Where price sits in the band",
            summary = "درصد باند از صفر یا یک برمی‌گردد.",
            summaryEn = "%B comes back from zero or one.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
                ScriptLibraryInput("width", 2, "انحراف", "Deviation", 1, 5),
            ),
            lines = listOf(
                "place = ta.bb_percent(close, span, width)",
            ),
            plots = listOf(
                ScriptLibraryPlot("place", "%B", "%B", "color.gold", "own"),
            ),
            bias = "place < 0.5",
            up = "ta.crossover(place, 0)",
            down = "ta.crossunder(place, 1)",
            upText = "از کف باند برگشت",
            upTextEn = "It came back off the band's floor",
            downText = "از سقف باند برگشت",
            downTextEn = "It came back off the band's ceiling",
        ),
        ScriptLibraryEntry(
            id = "fisher-turn",
            family = ScriptFamily.REVERSION,
            title = "چرخش فیشر",
            titleEn = "The Fisher transform turns",
            summary = "تبدیل فیشر از خط سیگنالش رد می‌شود.",
            summaryEn = "The Fisher transform crosses its signal.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 9, "دوره", "Length", 2, 100),
            ),
            lines = listOf(
                "fisherLine = ta.fisher(span)",
                "signalLine = ta.fisher_signal(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("fisherLine", "فیشر", "Fisher", "color.gold", "own"),
                ScriptLibraryPlot("signalLine", "سیگنال", "Signal", "color.blue", "own"),
            ),
            bias = "fisherLine > signalLine",
            up = "ta.crossover(fisherLine, signalLine)",
            down = "ta.crossunder(fisherLine, signalLine)",
            upText = "فیشر رو به بالا چرخید",
            upTextEn = "Fisher turned up",
            downText = "فیشر رو به پایین چرخید",
            downTextEn = "Fisher turned down",
        ),
        ScriptLibraryEntry(
            id = "volume-spike",
            family = ScriptFamily.VOLUME,
            title = "جهش حجم",
            titleEn = "A jump in volume",
            summary = "حجم چند برابر میانگینش می‌شود.",
            summaryEn = "Volume goes to a multiple of its own average.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
                ScriptLibraryInput("times", 2, "چند برابر", "Multiple", 1, 10),
            ),
            lines = listOf(
                "usual = ta.sma(volume, span)",
                "loud = volume > usual * times",
            ),
            plots = listOf(
                ScriptLibraryPlot("volume", "حجم", "Volume", "color.grey", "own"),
                ScriptLibraryPlot("usual * times", "آستانه", "Threshold", "color.gold", "own"),
            ),
            bias = "close > open",
            up = "loud and close > open",
            down = "loud and close < open",
            upText = "جهش حجم با کندل صعودی",
            upTextEn = "A volume spike on a rising bar",
            downText = "جهش حجم با کندل نزولی",
            downTextEn = "A volume spike on a falling bar",
        ),
        ScriptLibraryEntry(
            id = "obv-trend",
            family = ScriptFamily.VOLUME,
            title = "روند حجم متوازن",
            titleEn = "On-balance volume trends",
            summary = "OBV از میانگین خودش رد می‌شود.",
            summaryEn = "OBV crosses its own average.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
            ),
            lines = listOf(
                "balance = ta.obv()",
                "usual = ta.sma(balance, span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("balance", "OBV", "OBV", "color.gold", "own"),
                ScriptLibraryPlot("usual", "میانگین", "Average", "color.blue", "own"),
            ),
            bias = "balance > usual",
            up = "ta.crossover(balance, usual)",
            down = "ta.crossunder(balance, usual)",
            upText = "حجم متوازن بالای میانگینش رفت",
            upTextEn = "OBV went over its average",
            downText = "حجم متوازن زیر میانگینش رفت",
            downTextEn = "OBV went under its average",
        ),
        ScriptLibraryEntry(
            id = "cmf-zero",
            family = ScriptFamily.VOLUME,
            title = "چرخش جریان پول چایکین",
            titleEn = "Chaikin money flow turns",
            summary = "جریان پول چایکین علامتش را عوض می‌کند.",
            summaryEn = "Chaikin money flow changes sign.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
            ),
            lines = listOf(
                "flow = ta.cmf(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("flow", "CMF", "CMF", "color.gold", "own"),
            ),
            bias = "flow > 0",
            up = "ta.crossover(flow, 0)",
            down = "ta.crossunder(flow, 0)",
            upText = "جریان پول مثبت شد",
            upTextEn = "Money flow turned positive",
            downText = "جریان پول منفی شد",
            downTextEn = "Money flow turned negative",
        ),
        ScriptLibraryEntry(
            id = "mfi-extremes",
            family = ScriptFamily.VOLUME,
            title = "بازگشت شاخص جریان پول",
            titleEn = "The money flow index comes back",
            summary = "MFI از کف یا سقفش برمی‌گردد.",
            summaryEn = "MFI comes back from its floor or ceiling.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 200),
            ),
            lines = listOf(
                "flow = ta.mfi(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("flow", "MFI", "MFI", "color.gold", "own"),
            ),
            bias = "flow < 50",
            up = "ta.crossover(flow, 20)",
            down = "ta.crossunder(flow, 80)",
            upText = "MFI از کف برگشت",
            upTextEn = "MFI came back over its floor",
            downText = "MFI از سقف پایین آمد",
            downTextEn = "MFI came back under its ceiling",
        ),
        ScriptLibraryEntry(
            id = "vwma-cross",
            family = ScriptFamily.VOLUME,
            title = "عبور از میانگین وزنی حجم",
            titleEn = "Crossing the volume-weighted average",
            summary = "قیمت از میانگینی که حجم را وزن می‌دهد رد می‌شود.",
            summaryEn = "Price crosses an average weighted by volume.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
            ),
            lines = listOf(
                "weighted = ta.vwma(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("weighted", "VWMA", "VWMA", "color.gold", "price"),
            ),
            bias = "close > weighted",
            up = "ta.crossover(close, weighted)",
            down = "ta.crossunder(close, weighted)",
            upText = "قیمت بالای میانگین وزنی رفت",
            upTextEn = "Price went over the weighted average",
            downText = "قیمت زیر میانگین وزنی رفت",
            downTextEn = "Price went under the weighted average",
        ),
        ScriptLibraryEntry(
            id = "force-zero",
            family = ScriptFamily.VOLUME,
            title = "چرخش شاخص نیرو",
            titleEn = "The force index turns",
            summary = "شاخص نیروی الدر علامتش را عوض می‌کند.",
            summaryEn = "Elder's force index changes sign.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 13, "دوره", "Length", 2, 100),
            ),
            lines = listOf(
                "push = ta.force(span)",
            ),
            plots = listOf(
                ScriptLibraryPlot("push", "نیرو", "Force", "color.gold", "own"),
            ),
            bias = "push > 0",
            up = "ta.crossover(push, 0)",
            down = "ta.crossunder(push, 0)",
            upText = "نیرو مثبت شد",
            upTextEn = "Force turned positive",
            downText = "نیرو منفی شد",
            downTextEn = "Force turned negative",
        ),
        ScriptLibraryEntry(
            id = "klinger-signal",
            family = ScriptFamily.VOLUME,
            title = "تقاطع کلینگر",
            titleEn = "Klinger crosses its signal",
            summary = "اوسیلاتور حجمی کلینگر از سیگنالش رد می‌شود.",
            summaryEn = "The Klinger volume oscillator crosses its signal.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "klingerLine = ta.klinger(34, 55, 13)",
                "signalLine = ta.klinger_signal(34, 55, 13)",
            ),
            plots = listOf(
                ScriptLibraryPlot("klingerLine", "کلینگر", "Klinger", "color.gold", "own"),
                ScriptLibraryPlot("signalLine", "سیگنال", "Signal", "color.blue", "own"),
            ),
            bias = "klingerLine > signalLine",
            up = "ta.crossover(klingerLine, signalLine)",
            down = "ta.crossunder(klingerLine, signalLine)",
            upText = "کلینگر از سیگنالش رد شد",
            upTextEn = "Klinger crossed above its signal",
            downText = "کلینگر زیر سیگنالش رفت",
            downTextEn = "Klinger crossed below its signal",
        ),
        ScriptLibraryEntry(
            id = "chaikin-osc",
            family = ScriptFamily.VOLUME,
            title = "چرخش اوسیلاتور چایکین",
            titleEn = "The Chaikin oscillator turns",
            summary = "اوسیلاتور چایکین علامتش را عوض می‌کند.",
            summaryEn = "The Chaikin oscillator changes sign.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "flow = ta.chaikin_osc(3, 10)",
            ),
            plots = listOf(
                ScriptLibraryPlot("flow", "چایکین", "Chaikin", "color.gold", "own"),
            ),
            bias = "flow > 0",
            up = "ta.crossover(flow, 0)",
            down = "ta.crossunder(flow, 0)",
            upText = "چایکین مثبت شد",
            upTextEn = "Chaikin turned positive",
            downText = "چایکین منفی شد",
            downTextEn = "Chaikin turned negative",
        ),
        ScriptLibraryEntry(
            id = "structure-break",
            family = ScriptFamily.SMART_MONEY,
            title = "شکست ساختار",
            titleEn = "A break of structure",
            summary = "قیمت آخرین سقف یا کف ساختاری را می‌شکند.",
            summaryEn = "Price takes out the last structural high or low.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("wing", 5, "بال پیوت", "Pivot wing", 1, 30),
            ),
            lines = listOf(
                "lastHigh = ta.valuewhen(not na(ta.pivothigh(wing, wing)), high[wing], 0)",
                "lastLow = ta.valuewhen(not na(ta.pivotlow(wing, wing)), low[wing], 0)",
            ),
            plots = listOf(
                ScriptLibraryPlot("lastHigh", "سقف ساختاری", "Structural high", "color.sell", "price"),
                ScriptLibraryPlot("lastLow", "کف ساختاری", "Structural low", "color.buy", "price"),
            ),
            bias = "close > lastHigh",
            up = "ta.crossover(close, lastHigh)",
            down = "ta.crossunder(close, lastLow)",
            upText = "ساختار رو به بالا شکست",
            upTextEn = "Structure broke upwards",
            downText = "ساختار رو به پایین شکست",
            downTextEn = "Structure broke downwards",
        ),
        ScriptLibraryEntry(
            id = "liquidity-sweep",
            family = ScriptFamily.SMART_MONEY,
            title = "جاروی نقدینگی",
            titleEn = "A liquidity sweep",
            summary = "کندل از کف قبلی رد می‌شود و بالاتر از آن بسته می‌شود.",
            summaryEn = "A bar takes out the prior low and closes back above it.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 20, "دوره", "Length", 2, 200),
            ),
            lines = listOf(
                "priorLow = ta.lowest(low, span)[1]",
                "priorHigh = ta.highest(high, span)[1]",
                "sweptLow = low < priorLow and close > priorLow",
                "sweptHigh = high > priorHigh and close < priorHigh",
            ),
            plots = listOf(
                ScriptLibraryPlot("priorLow", "کف قبلی", "Prior low", "color.buy", "price"),
                ScriptLibraryPlot("priorHigh", "سقف قبلی", "Prior high", "color.sell", "price"),
            ),
            bias = "sweptLow",
            up = "sweptLow",
            down = "sweptHigh",
            upText = "کف جارو شد و قیمت برگشت",
            upTextEn = "The low was swept and price came back",
            downText = "سقف جارو شد و قیمت برگشت",
            downTextEn = "The high was swept and price came back",
        ),
        ScriptLibraryEntry(
            id = "fair-value-gap",
            family = ScriptFamily.SMART_MONEY,
            title = "شکاف ارزش منصفانه",
            titleEn = "A fair-value gap",
            summary = "بین سایه‌ی دو کندل فاصله می‌افتد.",
            summaryEn = "A gap opens between two bars' wicks.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "gapUp = low > high[2]",
                "gapDown = high < low[2]",
            ),
            plots = emptyList(),
            bias = "gapUp",
            up = "gapUp",
            down = "gapDown",
            upText = "شکاف صعودی باز شد",
            upTextEn = "A rising gap opened",
            downText = "شکاف نزولی باز شد",
            downTextEn = "A falling gap opened",
        ),
        ScriptLibraryEntry(
            id = "displacement",
            family = ScriptFamily.SMART_MONEY,
            title = "جابه‌جایی",
            titleEn = "Displacement",
            summary = "کندلی چند برابر دامنه‌ی معمول با بدنه‌ی پر.",
            summaryEn = "A bar several times the usual range, with a full body.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 14, "دوره", "Length", 2, 200),
                ScriptLibraryInput("times", 2, "چند برابر", "Multiple", 1, 8),
            ),
            lines = listOf(
                "usual = ta.atr(span)",
                "body = math.abs(close - open)",
                "big = body > usual * times",
            ),
            plots = emptyList(),
            bias = "close > open",
            up = "big and close > open",
            down = "big and close < open",
            upText = "جابه‌جایی صعودی",
            upTextEn = "A rising displacement",
            downText = "جابه‌جایی نزولی",
            downTextEn = "A falling displacement",
        ),
        ScriptLibraryEntry(
            id = "premium-discount",
            family = ScriptFamily.SMART_MONEY,
            title = "بالا یا پایین میانه‌ی دامنه",
            titleEn = "Above or below the range's middle",
            summary = "قیمت از نیمه‌ی دامنه‌ی n کندل رد می‌شود.",
            summaryEn = "Price crosses the midpoint of the last n bars' range.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 50, "دوره", "Length", 2, 400),
            ),
            lines = listOf(
                "top = ta.highest(high, span)",
                "bottom = ta.lowest(low, span)",
                "middle = (top + bottom) / 2",
            ),
            plots = listOf(
                ScriptLibraryPlot("middle", "میانه‌ی دامنه", "Range middle", "color.gold", "price"),
                ScriptLibraryPlot("top", "سقف", "Top", "color.sell", "price"),
                ScriptLibraryPlot("bottom", "کف", "Bottom", "color.buy", "price"),
            ),
            bias = "close > middle",
            up = "ta.crossover(close, middle)",
            down = "ta.crossunder(close, middle)",
            upText = "قیمت به نیمه‌ی بالای دامنه رفت",
            upTextEn = "Price moved into the range's upper half",
            downText = "قیمت به نیمه‌ی پایین دامنه رفت",
            downTextEn = "Price moved into the range's lower half",
        ),
        ScriptLibraryEntry(
            id = "equal-levels",
            family = ScriptFamily.SMART_MONEY,
            title = "سقف و کف برابر",
            titleEn = "Equal highs and lows",
            summary = "سقف یا کف چند کندل تقریباً یکی است و بعد شکسته می‌شود.",
            summaryEn = "Several bars share a high or a low, and then it breaks.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("span", 10, "دوره", "Length", 2, 100),
            ),
            lines = listOf(
                "top = ta.highest(high, span)",
                "bottom = ta.lowest(low, span)",
                "flatTop = math.abs(top - top[span]) < ta.atr(14) * 0.1",
                "flatBottom = math.abs(bottom - bottom[span]) < ta.atr(14) * 0.1",
            ),
            plots = listOf(
                ScriptLibraryPlot("top", "سقف", "Top", "color.sell", "price"),
                ScriptLibraryPlot("bottom", "کف", "Bottom", "color.buy", "price"),
            ),
            bias = "close > top[1]",
            up = "flatTop[1] and close > top[1]",
            down = "flatBottom[1] and close < bottom[1]",
            upText = "سقف‌های برابر شکست",
            upTextEn = "The equal highs broke",
            downText = "کف‌های برابر شکست",
            downTextEn = "The equal lows broke",
        ),
        ScriptLibraryEntry(
            id = "pullback-continuation",
            family = ScriptFamily.SMART_MONEY,
            title = "ادامه بعد از پولبک",
            titleEn = "Continuing after a pullback",
            summary = "در روند، قیمت به میانگین برمی‌گردد و دوباره راه می‌افتد.",
            summaryEn = "Inside a trend, price returns to the average and goes on.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("trendLen", 200, "دوره‌ی روند", "Trend length", 10, 400),
                ScriptLibraryInput("pullLen", 20, "دوره‌ی پولبک", "Pullback length", 2, 200),
            ),
            lines = listOf(
                "trend = ta.ema(close, trendLen)",
                "pull = ta.ema(close, pullLen)",
                "rising = close > trend",
            ),
            plots = listOf(
                ScriptLibraryPlot("trend", "روند", "Trend", "color.blue", "price"),
                ScriptLibraryPlot("pull", "پولبک", "Pullback", "color.gold", "price"),
            ),
            bias = "rising",
            up = "rising and ta.crossover(close, pull)",
            down = "not rising and ta.crossunder(close, pull)",
            upText = "پولبک در روند صعودی تمام شد",
            upTextEn = "The pullback in a rising trend ended",
            downText = "پولبک در روند نزولی تمام شد",
            downTextEn = "The pullback in a falling trend ended",
        ),
        ScriptLibraryEntry(
            id = "wick-rejection",
            family = ScriptFamily.SMART_MONEY,
            title = "پس زدن با سایه",
            titleEn = "A wick rejection",
            summary = "کندلی با سایه‌ی بلند و بدنه‌ی کوچک.",
            summaryEn = "A bar with a long wick and a small body.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("share", 2, "نسبت سایه به بدنه", "Wick-to-body ratio", 1, 8),
            ),
            lines = listOf(
                "body = math.abs(close - open)",
                "lowerWick = math.min(open, close) - low",
                "upperWick = high - math.max(open, close)",
            ),
            plots = emptyList(),
            bias = "lowerWick > upperWick",
            up = "lowerWick > body * share and close > open",
            down = "upperWick > body * share and close < open",
            upText = "سایه‌ی پایین بلند، قیمت پس زده شد",
            upTextEn = "A long lower wick: price was pushed back up",
            downText = "سایه‌ی بالا بلند، قیمت پس زده شد",
            downTextEn = "A long upper wick: price was pushed back down",
        ),
        ScriptLibraryEntry(
            id = "inefficiency-fill",
            family = ScriptFamily.SMART_MONEY,
            title = "پر شدن شکاف",
            titleEn = "A gap fills",
            summary = "قیمت به شکافی که جا گذاشته بود برمی‌گردد.",
            summaryEn = "Price returns to the gap it left behind.",
            stopAtr = 2,
            inputs = emptyList(),
            lines = listOf(
                "gapUp = low[1] > high[3]",
                "gapDown = high[1] < low[3]",
            ),
            plots = emptyList(),
            bias = "gapUp",
            up = "gapUp and low <= high[3]",
            down = "gapDown and high >= low[3]",
            upText = "شکاف صعودی پر شد",
            upTextEn = "The rising gap filled",
            downText = "شکاف نزولی پر شد",
            downTextEn = "The falling gap filled",
        ),
        ScriptLibraryEntry(
            id = "session-sweep",
            family = ScriptFamily.SMART_MONEY,
            title = "برداشتن سقف روز قبل",
            titleEn = "Taking yesterday's high",
            summary = "قیمت سقف یا کف کندل مرجع را برمی‌دارد و برمی‌گردد.",
            summaryEn = "Price takes the reference bar's high or low and comes back.",
            stopAtr = 2,
            inputs = listOf(
                ScriptLibraryInput("back", 24, "کندل مرجع", "Reference bar", 1, 200),
            ),
            lines = listOf(
                "priorHigh = ta.highest(high, back)[1]",
                "priorLow = ta.lowest(low, back)[1]",
            ),
            plots = listOf(
                ScriptLibraryPlot("priorHigh", "سقف مرجع", "Reference high", "color.sell", "price"),
                ScriptLibraryPlot("priorLow", "کف مرجع", "Reference low", "color.buy", "price"),
            ),
            bias = "close > priorLow",
            up = "low < priorLow and close > priorLow",
            down = "high > priorHigh and close < priorHigh",
            upText = "کف مرجع برداشته شد و قیمت برگشت",
            upTextEn = "The reference low was taken and price came back",
            downText = "سقف مرجع برداشته شد و قیمت برگشت",
            downTextEn = "The reference high was taken and price came back",
        ),
    )

    /** The entries on one shelf, in the order they were written. */
    fun of(family: ScriptFamily): List<ScriptLibraryEntry> = ALL.filter { it.family == family }

    val BY_ID: Map<String, ScriptLibraryEntry> = ALL.associateBy { it.id }
}
