package com.coinepro.core.script

/**
 * The reference in English: one line per function, keyed by the name before the parenthesis.
 *
 * [ScriptReference] is written in Persian, the language the app speaks first; this is the same
 * table for a reader whose app is in English. Keyed by name rather than by full signature so a
 * changed default in the Persian table does not orphan its translation. `ReferenceDocsTest`
 * fails when a Persian entry has no English line here, so the two cannot drift apart.
 */
object ScriptReferenceEn {

    val RETURNS: Map<String, String> = mapOf(
        "سری عددی" to "number series",
        "سری شرطی" to "condition series",
        "عدد" to "number",
        "عدد یا سری" to "number or series",
        "درست/نادرست" to "true/false",
        "رنگ" to "colour",
    )

    val SUMMARIES: Map<String, String> = mapOf(
        // Built-in series.
        "close" to "Each bar's closing price.",
        "open" to "Each bar's opening price.",
        "high" to "Each bar's highest price.",
        "low" to "Each bar's lowest price.",
        "volume" to "Each bar's volume. Absent on symbols whose feed sends none.",
        "hl2" to "The bar's midpoint: (high + low) ÷ 2.",
        "hlc3" to "The typical price: (high + low + close) ÷ 3.",
        "ohlc4" to "The mean of the bar's four prices.",
        "time" to "The bar's time, in Unix seconds.",
        "bar_index" to "The bar's number, from zero.",
        "n" to "How many bars the chart holds.",
        "confirmed" to "True on every closed bar and false on the last; end a signal with «and confirmed» so its mark never sits on the bar still forming.",
        // Averages.
        "ta.sma" to "Simple moving average over the length.",
        "ta.ema" to "Exponential moving average; weights recent bars more.",
        "ta.wma" to "Linearly weighted moving average.",
        "ta.hma" to "Hull moving average; less lag than EMA, longer warm-up.",
        "ta.smma" to "Smoothed moving average (RMA) — the one inside RSI and ATR.",
        "ta.zlema" to "Zero-lag exponential moving average.",
        "ta.kama" to "Kaufman's adaptive average: fast in a trend, slow in a range.",
        "ta.mcginley" to "McGinley Dynamic; an average that adjusts to the market's speed.",
        "ta.linreg" to "Linear regression over the window — the value at the line's end on each bar.",
        "ta.dema" to "Double exponential moving average; less lag than EMA.",
        "ta.tema" to "Triple exponential moving average.",
        "ta.t3" to "Tillson's T3 average with a volume factor.",
        "ta.vwma" to "Volume-weighted moving average of the chart's close.",
        "ta.alligator_jaw" to "Williams' Alligator jaw (SMMA 13, shifted 8).",
        "ta.alligator_teeth" to "Alligator teeth (SMMA 8, shifted 5).",
        "ta.alligator_lips" to "Alligator lips (SMMA 5, shifted 3).",
        // Oscillators.
        "ta.rsi" to "Relative strength index, 0 to 100.",
        "ta.cci" to "Commodity channel index. Reads the chart's own high, low and close.",
        "ta.atr" to "Average true range — the size of the moves, not their direction.",
        "ta.macd" to "The MACD line: the difference of two exponential averages.",
        "ta.macd_signal" to "The MACD signal line.",
        "ta.macd_hist" to "The MACD histogram: line minus signal.",
        "ta.momentum" to "Price minus the price a number of bars ago.",
        "ta.williams_r" to "Williams %R, 0 to −100. Reads the chart's high, low and close.",
        "ta.ultimate" to "Larry Williams' Ultimate Oscillator over three periods.",
        "ta.trix" to "TRIX: the rate of change of a triple exponential average.",
        "ta.trix_signal" to "The TRIX signal line.",
        "ta.fisher" to "Fisher transform of the bar midpoint; sharpens turns.",
        "ta.fisher_signal" to "The Fisher signal line (one bar behind).",
        "ta.crsi" to "Connors RSI: the mean of a short RSI, a streak RSI and a percent rank.",
        "ta.smi" to "SMI ergodic (TSI form), −100 to 100.",
        "ta.smi_signal" to "The SMI signal line.",
        "ta.chop" to "Choppiness index; above 61 a range, below 38 a trend.",
        "ta.bop" to "Balance of power: (close − open) ÷ (high − low), optionally smoothed.",
        "ta.vortex_plus" to "The positive Vortex line.",
        "ta.vortex_minus" to "The negative Vortex line.",
        "ta.tr" to "Each bar's true range, unaveraged.",
        "ta.hv" to "Historical volatility: the standard deviation of log returns, annualised.",
        "ta.chaikin_vol" to "Chaikin volatility: the rate of change of the average bar range.",
        "ta.bb_percent" to "%B: where price sits between the Bollinger bands, 0 to 1.",
        "ta.bb_width" to "Bollinger band width relative to the basis.",
        "ta.ppo" to "Percentage price oscillator: MACD divided by the slow average, in percent.",
        "ta.ppo_signal" to "The PPO signal line.",
        "ta.pvo" to "Percentage volume oscillator.",
        "ta.pvo_signal" to "The PVO signal line.",
        "ta.tsi" to "True strength index; momentum smoothed twice.",
        "ta.tsi_signal" to "The TSI signal line.",
        "ta.stochrsi_k" to "Stochastic of RSI, the K line.",
        "ta.stochrsi_d" to "Stochastic of RSI, the D line.",
        "ta.ao" to "Awesome Oscillator: SMA 5 minus SMA 34 of the bar midpoint.",
        "ta.ac" to "Accelerator: AO minus its own SMA 5.",
        "ta.cmo" to "Chande momentum oscillator.",
        "ta.coppock" to "Coppock curve: a WMA of the sum of two ROCs.",
        "ta.rvi" to "Relative vigor index over the chart's open, high, low and close.",
        "ta.rvi_signal" to "The RVI signal line.",
        "ta.kst" to "Know Sure Thing: four smoothed ROCs weighted 1 to 4.",
        "ta.kst_signal" to "The KST signal line (SMA 9).",
        "ta.dpo" to "Detrended price oscillator: price minus a displaced average.",
        "ta.variance" to "The window's variance (the standard deviation squared).",
        "ta.avg" to "The window's simple mean; ta.sma by a shorter name.",
        // Bands and trend.
        "ta.keltner_upper" to "The upper Keltner channel (EMA ± multiplier × ATR).",
        "ta.keltner_lower" to "The lower Keltner channel.",
        "ta.keltner_basis" to "The Keltner channel's middle.",
        "ta.env_upper" to "The upper envelope: the simple average plus a percentage.",
        "ta.env_lower" to "The lower envelope.",
        "ta.env_basis" to "The envelope's middle.",
        "ta.bb_basis" to "The Bollinger band's middle.",
        "ta.bb_upper" to "The upper Bollinger band.",
        "ta.bb_lower" to "The lower Bollinger band.",
        "ta.donchian_upper" to "The Donchian channel's top. For a breakout read it one bar back: ta.donchian_upper(20)[1].",
        "ta.donchian_lower" to "The Donchian channel's bottom.",
        "ta.supertrend" to "The SuperTrend line: an ATR-sized band that changes side with price.",
        "ta.supertrend_trend" to "SuperTrend direction: 1 rising, −1 falling. A change of sign is the reversal.",
        "ta.adx" to "Trend strength without direction. Below the threshold there is no trend.",
        "ta.di_plus" to "The positive directional index.",
        "ta.di_minus" to "The negative directional index.",
        "ta.stoch_k" to "The stochastic %K line.",
        "ta.stoch_d" to "The stochastic %D line; the average of %K.",
        "ta.ichimoku_conversion" to "Tenkan-sen.",
        "ta.ichimoku_base" to "Kijun-sen.",
        "ta.ichimoku_span_a" to "Senkou span A, unshifted.",
        "ta.ichimoku_span_b" to "Senkou span B, unshifted.",
        "ta.psar" to "Wilder's parabolic SAR; the step and the maximum acceleration.",
        "ta.vstop" to "Volatility stop: ATR × multiplier from the trend's extreme.",
        "ta.aroon_up" to "Aroon up: what share of the period since the last high.",
        "ta.aroon_down" to "Aroon down.",
        "ta.mass" to "Dorsey's mass index; a bulge above 27 warns of a reversal.",
        "ta.correlation" to "Pearson correlation of two series over the window.",
        // Volume.
        "ta.obv" to "On-balance volume. Like vwap, absent without volume.",
        "ta.ad" to "The accumulation/distribution line.",
        "ta.pvt" to "Price-volume trend.",
        "ta.force" to "Elder's force index, smoothed with an exponential average.",
        "ta.chaikin_osc" to "The Chaikin oscillator: the difference of two averages of the A/D line.",
        "ta.eom" to "Ease of movement.",
        "ta.klinger" to "The Klinger volume oscillator.",
        "ta.klinger_signal" to "The Klinger signal line.",
        "ta.vwap" to "Volume-weighted average price from the first bar.",
        "ta.mfi" to "Money flow index: a volume-weighted RSI.",
        "ta.cmf" to "Chaikin money flow.",
        "ta.netvolume" to "Net volume: volume signed by the bar's direction.",
        // Windows and logic.
        "ta.highest" to "The highest value in the window.",
        "ta.lowest" to "The lowest value in the window.",
        "ta.sum" to "The window's sum.",
        "ta.stdev" to "The window's standard deviation.",
        "ta.change" to "The difference from a number of bars ago.",
        "ta.roc" to "Percent change from a number of bars ago.",
        "ta.cum" to "The cumulative sum from the first bar.",
        "ta.rising" to "True when the value rose on each of the last n bars.",
        "ta.falling" to "True when the value fell on each of the last n bars.",
        "ta.barssince" to "Bars since the condition last held; absent before its first time.",
        "ta.valuewhen" to "The series' value on the last bar the condition held; the third number says how many occurrences back.",
        "ta.pivothigh" to "A local top: higher than n bars before and n after. Sits on the bar that confirms it and never moves.",
        "ta.pivotlow" to "A local bottom, by the same rule.",
        "ta.crossover" to "The bar on which a crossed above b.",
        "ta.crossunder" to "The bar on which a crossed below b.",
        // Math.
        "math.abs" to "Absolute value.",
        "math.max" to "The larger of two values.",
        "math.min" to "The smaller of two values.",
        "math.round" to "Round to the nearest whole number.",
        "math.floor" to "Round down.",
        "math.ceil" to "Round up.",
        "math.sqrt" to "Square root.",
        "math.log" to "Natural logarithm.",
        "math.sign" to "The sign: −1, 0 or 1.",
        "math.pow" to "A power.",
        "math.exp" to "e to the power x.",
        "math.log10" to "Base-ten logarithm.",
        "math.sin" to "Sine (radians).",
        "math.cos" to "Cosine.",
        "math.tan" to "Tangent.",
        "math.avg" to "The mean of two values.",
        "math.clamp" to "Keeps x between two constant bounds.",
        // Helpers, inputs, output.
        "iff" to "On each bar, a if the condition holds, otherwise b.",
        "nz" to "Puts the given number wherever a bar has no value.",
        "input" to "A number the reader can change from the panel under the chart; step sets the slider's step.",
        "input.string" to "A choice among the options, shown as chips in the panel.",
        "input.source" to "A choice of price series: close, open, high, low, hl2, hlc3, ohlc4 or volume.",
        "input.color" to "A colour input, from the named colours.",
        "input.timeframe" to "A timeframe choice, for request.security.",
        "request.security" to "The expression computed on a coarser timeframe (a multiple of the chart's), each chart bar taking the last completed higher bar's value — no repainting.",
        "input.int" to "A number input rounded to a whole number.",
        "input.float" to "A decimal input; the same as input.",
        "input.bool" to "An on/off input.",
        "color.new" to "The same colour with a transparency percentage (0 to 100).",
        "plot" to "Draws a number series as a line.",
        "hline" to "A horizontal level.",
        "marker" to "A mark on every bar the condition holds.",
        "plotshape" to "The same as marker, with Pine's shape names: triangleup, triangledown, arrowup, arrowdown.",
        "plotchar" to "The same as marker.",
        "bgcolor" to "A background colour on every bar the condition holds.",
        "alertcondition" to "A named condition the alert centre can follow; true on the last bar if the condition holds there.",
        "signal" to "The trade idea from the last bar the condition held, with its risk-to-reward.",
        "log" to "A line in the studio's log.",
    )

    /** The English line for a Persian entry, by the name before its parenthesis. */
    fun summaryFor(function: ScriptFunction): String? = SUMMARIES[nameOf(function.signature)]

    fun nameOf(signature: String): String = signature.substringBefore('(').trim()
}
