#!/usr/bin/env python3
"""Build the five bottom-navigation icons in both weights, from the vendored outlines.

The archive under ``design/ui-icons/nav`` holds the **outline** weight only, exactly as the vendor
draws it. The filled weight — what marks the selected tab — is derived here rather than stored,
because for four of the five there is no published filled counterpart to store.

Deriving it is not a guess. Every one of these glyphs is a font conversion: a solid outer contour
with the counter drawn inside it as a second, oppositely wound subpath. That is literally how the
outline weight is constructed, so removing the counters gives back the solid shape the outline was
cut from — the same relationship Phosphor's regular and fill weights have to each other. A subpath
is treated as a counter when its bounding box sits inside another subpath's; a wick that runs past
its candle body is therefore kept, and a bell's clapper, which does not, is not.

AI is the exception and is stored as two files, because OKX publishes both weights of it.

Run this and the ten drawables are regenerated together::

    python3 scripts/design/build-nav-icons.py

Provenance is in ``design/README.md``. The owner directed these to be taken from the exchanges'
own sets and holds the licensing question; that decision is recorded there rather than argued here.
"""

from __future__ import annotations

import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
NAV = REPO / "design" / "ui-icons" / "nav"

SVG_NS = "http://www.w3.org/2000/svg"
PATH = f"{{{SVG_NS}}}path"

# Every number in the path data. Good enough for a bounding box on these files: they are font
# conversions and every coordinate is absolute, so the numbers are the points.
NUMBER = re.compile(r"[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?")

# The five destinations, in AppDestination order. The value is the outline file's stem; a name in
# PUBLISHED_FILL has its filled weight shipped by the vendor instead of derived.
ICONS = ("home", "signals", "ai", "tools", "activity")
PUBLISHED_FILL = {"ai"}


def subpaths(data: str) -> list[str]:
    """Split path data at every move-to, which is where a new contour begins."""
    return [part for part in re.split(r"(?=[Mm])", data) if part.strip()]


def bounds(subpath: str) -> tuple[float, float, float, float] | None:
    numbers = [float(value) for value in NUMBER.findall(subpath)]
    xs, ys = numbers[0::2], numbers[1::2]
    if not xs or not ys:
        return None
    return min(xs), min(ys), max(xs), max(ys)


def encloses(outer: tuple, inner: tuple, tolerance: float = 0.5) -> bool:
    return (
        outer != inner
        and inner[0] >= outer[0] - tolerance
        and inner[1] >= outer[1] - tolerance
        and inner[2] <= outer[2] + tolerance
        and inner[3] <= outer[3] + tolerance
    )


def solidify(data: str) -> str:
    """Drop every counter, leaving the outer contours — the outline glyph's filled weight."""
    parts = subpaths(data)
    boxes = [bounds(part) for part in parts]
    kept = [
        part
        for index, part in enumerate(parts)
        if boxes[index] is None
        or not any(
            boxes[other] and encloses(boxes[other], boxes[index])
            for other in range(len(parts))
            if other != index
        )
    ]
    return "".join(kept)


def write_fill(name: str) -> None:
    ET.register_namespace("", SVG_NS)
    tree = ET.parse(NAV / f"{name}.svg")
    for path in tree.getroot().iter(PATH):
        data = path.get("d")
        if data:
            path.set("d", solidify(data))
        # The counters are gone, so no winding rule should be able to punch them back in.
        path.set("fill-rule", "nonzero")
    (NAV / f"{name}_fill.svg").write_text(
        "<!-- Generated by scripts/design/build-nav-icons.py from "
        f"{name}.svg. Do not hand-edit. -->\n"
        + ET.tostring(tree.getroot(), encoding="unicode"),
        encoding="utf-8",
    )


def main() -> int:
    derived = [name for name in ICONS if name not in PUBLISHED_FILL]
    for name in derived:
        write_fill(name)

    names = [name for name in ICONS] + [f"{name}_fill" for name in ICONS]
    result = subprocess.run(
        [
            sys.executable, str(REPO / "scripts/design/svg-to-vector.py"),
            "--ui", "--set", "nav", "--prefix", "nav_", *names,
        ],
        cwd=REPO,
        text=True,
    )
    if result.returncode != 0:
        return result.returncode
    print(f"{len(names)} drawables, {len(derived)} filled weights derived")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
