#!/usr/bin/env python3
"""Assemble a before/after sheet for every golden a run changed.

### Why this exists

A run that redraws the chart re-records forty goldens, and «the after exists» is not the same claim
as «somebody looked at the pair». The point of a before/after is that a person can see, in one
image, what a version did — and the two frames have to be *beside* each other for that, because
flipping between two files in a viewer is how a moved baseline goes unnoticed.

### Why the sheets are composites and not two copies

The goldens are 17 MB for 139 files. Committing a before *and* an after for each run would add ten
megabytes a version to a repository that has to be cloned on a phone tether. A composite at half
width is about a fifth of that, is the thing somebody actually looks at, and the originals are both
still in git — the index names the exact `git show` for each, so the full-resolution pair is one
command away.

Usage:  python3 scripts/quality/gen_before_after.py <base-ref> [--out DIR]

`<base-ref>` is the commit the run started from; the *after* is the working tree.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
GOLDENS = "app/src/test/goldens"
DEFAULT_OUT = ROOT / "docs/qa/screenshots/before-after"

# Half of the widest golden this app records. Wide enough to read a legend and a strip, small enough
# that a whole run's worth of sheets is a megabyte or two.
PANEL_WIDTH = 560

# WEBP, not PNG. A chart is mostly flat colour and PNG is honest about every pixel of it — fifty-four
# PNG sheets came to nine megabytes, which is not a thing to add to a repository per version. At
# quality 80 the same sheets are under a megabyte and the difference is invisible at half width; the
# lossless originals are both still in git, one `git show` away, which is what the index is for.
QUALITY = 80

# The gutter between the two frames, in the stage colour the app itself uses, so a sheet does not
# look like a screenshot of a white page.
GUTTER = 16
GROUND = (11, 14, 17)


def changed_goldens(base: str) -> list[str]:
    out = subprocess.run(
        ["git", "diff", "--name-only", base, "--", GOLDENS],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [line for line in out.stdout.splitlines() if line.endswith(".png")]


def read_at(ref: str, path: str, into: Path) -> Path | None:
    """The file as it was at `ref`, written to a temporary. None where it did not exist yet."""
    result = subprocess.run(["git", "show", f"{ref}:{path}"], cwd=ROOT, capture_output=True)
    if result.returncode != 0:
        return None
    into.write_bytes(result.stdout)
    return into


def scaled(image: Image.Image) -> Image.Image:
    if image.width <= PANEL_WIDTH:
        return image
    height = round(image.height * PANEL_WIDTH / image.width)
    return image.resize((PANEL_WIDTH, height), Image.LANCZOS)


def compose(before: Image.Image, after: Image.Image) -> Image.Image:
    left, right = scaled(before), scaled(after)
    height = max(left.height, right.height)
    sheet = Image.new("RGB", (left.width + GUTTER + right.width, height), GROUND)
    # Before on the left, after on the right, in reading order for the Latin filename beneath it.
    sheet.paste(left.convert("RGB"), (0, 0))
    sheet.paste(right.convert("RGB"), (left.width + GUTTER, 0))
    return sheet


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    base = sys.argv[1]
    out = Path(sys.argv[3]) if len(sys.argv) > 3 and sys.argv[2] == "--out" else DEFAULT_OUT
    out.mkdir(parents=True, exist_ok=True)
    scratch = out / ".before.png"

    rows: list[tuple[str, str]] = []
    added: list[str] = []
    for path in changed_goldens(base):
        name = Path(path).stem
        old = read_at(base, path, scratch)
        new_path = ROOT / path
        if old is None or not new_path.exists():
            # A golden that did not exist before, or one the run deleted. Both are real outcomes and
            # neither is a pair; the index says which rather than the sheet pretending.
            added.append(name)
            continue
        sheet = compose(Image.open(old), Image.open(new_path))
        sheet.save(out / f"{name}.webp", quality=QUALITY, method=6)
        rows.append((name, path))
    scratch.unlink(missing_ok=True)

    index = out / "README.md"
    lines = [
        "# Before and after",
        "",
        f"Generated by `scripts/quality/gen_before_after.py {base}`; do not edit by hand.",
        "",
        "Each sheet is the golden as it was on the left and as it is now on the right, at half width.",
        "The originals are both in git at full resolution — the command beside each row is the one",
        "that gets the *before* back.",
        "",
        f"Base: `{base}`. Sheets: {len(rows)}.",
        "",
        "| golden | the before, at full resolution |",
        "| --- | --- |",
    ]
    for name, path in sorted(rows):
        lines.append(f"| `{name}` | `git show {base}:{path}` |")
    if added:
        lines += [
            "",
            "## Recorded by this run, so there is no before",
            "",
            *(f"- `{name}`" for name in sorted(added)),
        ]
    index.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(rows)} sheet(s) and {index.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
