#!/usr/bin/env python3
"""Write docs/qa/NAMASCRIPT_CONFORMANCE.md from the conformance suite: every script, its kind and
its expectations, so the suite can be read without opening 380 files. Run after adding a script;
`ConformanceSuiteTest` is the gate that the scripts pass, this is the index of what they claim."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SUITE = ROOT / "namascript/src/jvmTest/resources/conformance"
OUT = ROOT / "docs/qa/NAMASCRIPT_CONFORMANCE.md"
EXPECT = "// expect:"


def main() -> int:
    files = sorted(SUITE.glob("*.nama"))
    generated = [f for f in files if f.name.startswith("gen_")]
    semantic = [f for f in files if f.name.startswith("sem_")]
    lines = [
        "# NamaScript conformance suite — the index",
        "",
        f"Generated by `scripts/quality/gen_conformance_index.py` from `{SUITE.relative_to(ROOT)}`; do not edit by hand.",
        f"`ConformanceSuiteTest` runs every script below over one fixed 240-bar walk and holds it to the",
        f"expectations in its header. **{len(files)} scripts: {len(generated)} generated (`gen_`, one per",
        f"`ta.*` function and plot form, values recorded from the engine) and {len(semantic)} hand-written",
        "(`sem_`, one per language rule: absence, history, broadcasting, precedence, diagnostics, inputs,",
        "timeframes, text, objects, strategy).**",
        "",
        "| script | kind | expectations |",
        "| --- | --- | --- |",
    ]
    for f in files:
        expectations = [l.strip()[len(EXPECT):].strip() for l in f.read_text(encoding="utf-8").splitlines() if l.strip().startswith(EXPECT)]
        kind = "generated" if f.name.startswith("gen_") else "hand-written"
        summary = "; ".join(expectations)
        summary = re.sub(r"\s+", " ", summary)
        if len(summary) > 140:
            summary = summary[:137] + "…"
        lines.append(f"| `{f.name}` | {kind} | {summary} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(files)} scripts ({len(generated)} generated, {len(semantic)} hand-written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
