package com.coinepro.core.chart

import kotlin.math.abs
import kotlin.math.ln
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.sqrt

/**
 * The second thirty indicators, ported from Pro Chart's `indicators_ext_a.js` and
 * `indicators_ext_b.js`.
 *
 * Split from [Indicators] only because one file of fifty is unreadable; there is no other line
 * between them. Everything here is checked against the JavaScript by `IndicatorParityTest` over the
 * fixture in `core/chart/src/test/resources/indicator-parity.txt`, which is generated by
 * `scripts/design/generate-indicator-parity.mjs` and never hand-written.
 *
 * ### The two packs do not agree with each other, and that is deliberate here
 *
 * `indicators_ext_a.js` and `indicators_ext_b.js` each define their own `_sma`, `_ema` and `_stdev`,
 * and the definitions differ in how they treat a null in the *input*:
 *
 * * Pack A's EMA **skips** nulls and counts only the values it has seen, so a series with a long
 *   warm-up produces an EMA that starts `p` real samples after the first real value.
 * * Pack B's EMA **carries** the previous value across a null and starts emitting at index `p-1`
 *   regardless, so the same series produces an EMA that starts almost immediately.
 *
 * On a clean close series the two are identical. They diverge exactly where one indicator is fed
 * another's output — TRIX's signal line over TRIX, SMI's double smoothing — which is most of the
 * interesting ones. Where an indicator appears in both registries (TRIX, %B, bandwidth), pack B is
 * the one Pro Chart actually loads, so pack B is what is ported.
 *
 * Reproducing that split is not tidiness lost. It is the difference between an indicator that
 * matches the web terminal and one that is plausibly wrong — and a plausibly wrong indicator is the
 * worst kind, because nothing about the line it draws looks incorrect.
 */
object IndicatorsExt {

    // ══════════════════════════════════════════════════════════ trend and moving averages

    /**
     * Wilder's smoothed moving average, also called RMA.
     *
     * `(prev·(p−1) + value) / p`, seeded with a simple average of the first `p`. It is the average
     * inside RSI, ATR and ADX, and it is offered separately because a trader who wants "the
     * smoothing my RSI uses, on the price" has no other way to ask for it.
     */
    fun smma(source: DoubleArray, period: Int): Line = Line.from(packA.smma(source.toNullable(), period))

    /**
     * Zero-lag EMA: an EMA of the series plus its own momentum over half the period.
     *
     * The lag it removes is real — a 21-period EMA is on average ten bars behind — and the price of
     * removing it is overshoot at a turn. Which trade a reader wants is theirs to make; both are
     * offered.
     */
    fun zlema(source: DoubleArray, period: Int): Line {
        val lag = (period - 1) / 2
        val corrected = List(source.size) { index ->
            if (index < lag) null else source[index] + (source[index] - source[index - lag])
        }
        return Line.from(packA.ema(corrected, period))
    }

    /**
     * Kaufman's adaptive moving average.
     *
     * The smoothing constant moves with the efficiency ratio — net travel over gross travel — so it
     * tracks a trend closely and flattens in chop. That is the point: a fixed-period average is
     * always the wrong period for one of the two.
     */
    fun kama(source: DoubleArray, period: Int = 10, fast: Int = 2, slow: Int = 30): Line {
        val fastK = 2.0 / (fast + 1)
        val slowK = 2.0 / (slow + 1)
        val out = arrayOfNulls<Double>(source.size)
        var previous: Double? = null
        for (index in source.indices) {
            if (index < period) {
                if (index == period - 1) {
                    previous = source[index]
                    out[index] = previous
                }
                continue
            }
            val change = abs(source[index] - source[index - period])
            var travel = 0.0
            for (step in 0 until period) travel += abs(source[index - step] - source[index - step - 1])
            val efficiency = if (travel != 0.0) change / travel else 0.0
            val constant = (efficiency * (fastK - slowK) + slowK).pow(2)
            previous = previous!! + constant * (source[index] - previous)
            out[index] = previous
        }
        return Line.from(out.toList())
    }

    /** Tillson's T3: six chained EMAs recombined, with `volumeFactor` setting how much overshoot. */
    fun t3(source: DoubleArray, period: Int = 10, volumeFactor: Double = 0.7): Line {
        val values = source.toNullable()
        val e1 = packA.ema(values, period)
        val e2 = packA.ema(e1, period)
        val e3 = packA.ema(e2, period)
        val e4 = packA.ema(e3, period)
        val e5 = packA.ema(e4, period)
        val e6 = packA.ema(e5, period)
        val a = volumeFactor
        val c1 = -a * a * a
        val c2 = 3 * a * a + 3 * a * a * a
        val c3 = -6 * a * a - 3 * a - 3 * a * a * a
        val c4 = 1 + 3 * a + a * a * a + 3 * a * a
        return Line.of(source.size) { index ->
            val v6 = e6[index]
            val v5 = e5[index]
            val v4 = e4[index]
            val v3 = e3[index]
            if (v6 != null && v5 != null && v4 != null && v3 != null) {
                c1 * v6 + c2 * v5 + c3 * v4 + c4 * v3
            } else {
                null
            }
        }
    }

    /**
     * McGinley Dynamic.
     *
     * A self-adjusting average whose step is divided by `(price/average)^4`, so it speeds up when
     * price runs away from it and slows when price comes back. Seeded with a simple average.
     */
    fun mcginley(source: DoubleArray, period: Int = 14): Line {
        val out = arrayOfNulls<Double>(source.size)
        var value: Double? = null
        var sum = 0.0
        var count = 0
        for (index in source.indices) {
            val price = source[index]
            if (value == null) {
                sum += price
                count++
                if (count == period) {
                    value = sum / period
                    out[index] = value
                }
            } else {
                val ratio = if (value != 0.0) price / value else 1.0
                val denominator = period * ratio.pow(4)
                value += (price - value) / (if (denominator != 0.0) denominator else 1e-9)
                out[index] = value
            }
        }
        return Line.from(out.toList())
    }

    /**
     * Linear regression, evaluated at the end of the window.
     *
     * [offset] pushes the evaluation point past the window's end, which is what turns the same
     * calculation into an LSMA projection rather than a curve through the data.
     */
    fun linearRegression(source: DoubleArray, period: Int, offset: Int = 0): Line =
        Line.from(packA.linreg(source.toNullable(), period, offset))

    // ══════════════════════════════════════════════════════════ volatility

    /** Population standard deviation over a window — the `n`, not `n−1`, that Bollinger uses. */
    fun stdDev(source: DoubleArray, period: Int): Line = Line.from(packA.stdev(source.toNullable(), period))

    /**
     * Historical volatility: the annualised standard deviation of log returns, as a percentage.
     *
     * [annual] is 365 rather than 252 because crypto does not close. On a forex or index symbol a
     * reader who wants the trading-day convention sets it to 252 — the two are not comparable and
     * the difference is about twenty per cent.
     */
    fun historicalVolatility(close: DoubleArray, period: Int = 10, annual: Int = 365): Line {
        val returns = List(close.size) { index ->
            if (index == 0) {
                null
            } else if (close[index] > 0 && close[index - 1] > 0) {
                ln(close[index] / close[index - 1])
            } else {
                null
            }
        }
        val deviation = packA.stdev(returns, period)
        return Line.of(close.size) { index -> deviation[index]?.let { 100 * it * sqrt(annual.toDouble()) } }
    }

    /** Chaikin volatility: the percentage change in the smoothed high-low range over [rateOfChange] bars. */
    fun chaikinVolatility(
        high: DoubleArray,
        low: DoubleArray,
        period: Int = 10,
        rateOfChange: Int = 10,
    ): Line {
        val range = List(high.size) { high[it] - low[it] }
        val smoothed = packA.ema(range, period)
        return Line.of(high.size) { index ->
            val now = smoothed[index]
            val then = smoothed.getOrNull(index - rateOfChange)
            if (now != null && then != null && then != 0.0) 100 * (now - then) / then else null
        }
    }

    /** A percentage band around a simple average — the plainest channel there is. */
    fun envelopes(source: DoubleArray, period: Int = 20, percent: Double = 1.0): Band {
        val basis = packA.sma(source.toNullable(), period)
        return Band(
            basis = Line.from(basis),
            upper = Line.of(source.size) { basis[it]?.times(1 + percent / 100) },
            lower = Line.of(source.size) { basis[it]?.times(1 - percent / 100) },
        )
    }

    // ══════════════════════════════════════════════════════════ momentum

    /** Momentum: the plain difference over [period] bars. */
    fun momentum(source: DoubleArray, period: Int): Line = Line.of(source.size) { index ->
        if (index >= period) source[index] - source[index - period] else null
    }

    /** Rate of change, as a percentage. */
    fun rateOfChange(source: DoubleArray, period: Int): Line = Line.of(source.size) { index ->
        val base = if (index >= period) source[index - period] else return@of null
        if (base != 0.0) 100 * (source[index] - base) / base else null
    }

    /**
     * TRIX, in basis points, with its signal line.
     *
     * Pack B's version, which is the one the terminal loads: the signal EMA runs over the TRIX line
     * with nulls read as zero and is then masked back to where the line exists. Pack A's would warm
     * up nine samples later.
     */
    fun trix(source: DoubleArray, period: Int = 18, signalPeriod: Int = 9): LinePair {
        val values = source.toNullable()
        val third = packB.ema(packB.ema(packB.ema(values, period), period), period)
        val line = List(source.size) { index ->
            val now = third[index]
            val then = third.getOrNull(index - 1)
            if (index > 0 && now != null && then != null && then != 0.0) 10_000 * (now - then) / then else null
        }
        return LinePair(Line.from(line), Line.from(packB.emaMasked(line, signalPeriod)))
    }

    /**
     * Bill Williams' Accelerator: the awesome oscillator minus its own five-bar average.
     *
     * Returned as a histogram because that is how it is read — the sign is the signal and the
     * change of colour is the trigger.
     */
    fun accelerator(high: DoubleArray, low: DoubleArray): Line {
        val median = List(high.size) { (high[it] + low[it]) / 2 }
        val fast = packB.sma(median, 5)
        val slow = packB.sma(median, 34)
        val awesome = List(high.size) { index ->
            val f = fast[index]
            val s = slow[index]
            if (f != null && s != null) f - s else null
        }
        val average = packB.sma(awesome.map { it ?: 0.0 }, 5)
        return Line.of(high.size) { index ->
            val value = awesome[index]
            val mean = average[index]
            if (value != null && mean != null) value - mean else null
        }
    }

    /**
     * The Ultimate Oscillator: buying pressure over true range at three horizons, weighted 4:2:1.
     *
     * Three horizons because the whole reason Williams built it was that a single-period oscillator
     * gives a divergence signal that depends entirely on the period somebody happened to pick.
     */
    fun ultimateOscillator(
        high: DoubleArray,
        low: DoubleArray,
        close: DoubleArray,
        short: Int = 7,
        mid: Int = 14,
        long: Int = 28,
    ): Line {
        val size = close.size
        val pressure = arrayOfNulls<Double>(size)
        val range = arrayOfNulls<Double>(size)
        for (index in 1 until size) {
            val lowest = min(low[index], close[index - 1])
            val highest = max(high[index], close[index - 1])
            pressure[index] = close[index] - lowest
            range[index] = highest - lowest
        }
        fun window(source: Array<Double?>, length: Int, at: Int): Double? {
            var total = 0.0
            for (step in 0 until length) {
                total += source.getOrNull(at - step) ?: return null
            }
            return total
        }
        val longest = maxOf(short, mid, long)
        return Line.of(size) { index ->
            if (index < longest) return@of null
            val bs = window(pressure, short, index) ?: return@of null
            val bm = window(pressure, mid, index) ?: return@of null
            val bl = window(pressure, long, index) ?: return@of null
            val ts = window(range, short, index)
            val tm = window(range, mid, index)
            val tl = window(range, long, index)
            val a1 = bs / (ts.orEpsilon())
            val a2 = bm / (tm.orEpsilon())
            val a3 = bl / (tl.orEpsilon())
            100 * (4 * a1 + 2 * a2 + a3) / 7
        }
    }

    /**
     * The Fisher Transform, with its signal.
     *
     * The signal is the *previous bar's* value rather than an average of the line, which is what
     * makes the crossover as early as it is — and is also why it whipsaws in chop.
     */
    fun fisherTransform(high: DoubleArray, low: DoubleArray, period: Int = 9): LinePair {
        val median = List(high.size) { (high[it] + low[it]) / 2 }
        val highest = packB.highest(median, period)
        val lowest = packB.lowest(median, period)
        val line = arrayOfNulls<Double>(high.size)
        val signal = arrayOfNulls<Double>(high.size)
        var smoothed = 0.0
        var fisher = 0.0
        for (index in high.indices) {
            val top = highest[index] ?: continue
            val bottom = lowest[index] ?: continue
            val span = (top - bottom).let { if (it != 0.0) it else 1e-9 }
            var x = 0.66 * ((median[index] - bottom) / span - 0.5) + 0.67 * smoothed
            x = x.coerceIn(-0.999, 0.999)
            smoothed = x
            val previous = fisher
            fisher = 0.5 * ln((1 + x) / (1 - x)) + 0.5 * fisher
            line[index] = fisher
            signal[index] = previous
        }
        return LinePair(Line.from(line.toList()), Line.from(signal.toList()))
    }

    /**
     * Connors RSI: the average of an RSI of price, an RSI of the up/down streak, and the percentile
     * rank of the one-bar return.
     *
     * Three unrelated views of the same bar, which is the design — it is a mean-reversion measure
     * rather than a momentum one, and a plain RSI at these periods would be noise.
     */
    fun connorsRsi(
        close: DoubleArray,
        rsiLength: Int = 3,
        streakLength: Int = 2,
        rankLength: Int = 100,
    ): Line {
        val priceRsi = packB.rsi(close.toNullable(), rsiLength)
        val streak = packB.streak(close)
        val streakRsi = packB.rsi(streak.map { it.toDouble() }, streakLength)
        val returns = List(close.size) { index ->
            if (index == 0) null else if (close[index - 1] != 0.0) {
                100 * (close[index] - close[index - 1]) / close[index - 1]
            } else {
                0.0
            }
        }
        val rank = packB.percentRank(returns, rankLength)
        return Line.of(close.size) { index ->
            val a = priceRsi[index]
            val b = streakRsi[index]
            val c = rank[index]
            if (a != null && b != null && c != null) (a + b + c) / 3 else null
        }
    }

    /** SMI Ergodic — Blau's true strength index, with an EMA signal. */
    fun smiErgodic(close: DoubleArray, long: Int = 20, short: Int = 5, signalPeriod: Int = 5): LinePair {
        val change = List(close.size) { if (it == 0) 0.0 else close[it] - close[it - 1] }
        val magnitude = change.map { abs(it!!) }
        val smoothed = packB.ema(packB.ema(change, long), short)
        val smoothedMagnitude = packB.ema(packB.ema(magnitude, long), short)
        val line = List(close.size) { index ->
            val numerator = smoothed[index]
            val denominator = smoothedMagnitude[index]
            if (numerator != null && denominator != null && denominator != 0.0) {
                100 * numerator / denominator
            } else {
                null
            }
        }
        return LinePair(Line.from(line), Line.from(packB.emaMasked(line, signalPeriod)))
    }

    /**
     * The Stochastic Momentum Index: where close sits relative to the *midpoint* of the range,
     * doubly smoothed.
     *
     * Against the midpoint rather than the low, which is what separates it from a plain stochastic
     * and is why it reads −100..100 rather than 0..100.
     */
    fun stochasticMomentum(
        high: DoubleArray,
        low: DoubleArray,
        close: DoubleArray,
        period: Int = 10,
        smoothK: Int = 3,
        smoothD: Int = 3,
    ): Line {
        val highest = packB.highest(high.toNullable(), period)
        val lowest = packB.lowest(low.toNullable(), period)
        val relative = arrayOfNulls<Double>(close.size)
        val range = arrayOfNulls<Double>(close.size)
        for (index in close.indices) {
            val top = highest[index] ?: continue
            val bottom = lowest[index] ?: continue
            relative[index] = close[index] - (top + bottom) / 2
            range[index] = top - bottom
        }
        val smoothedRelative = packB.ema(packB.ema(relative.map { it ?: 0.0 }, smoothK), smoothD)
        val smoothedRange = packB.ema(packB.ema(range.map { it ?: 0.0 }, smoothK), smoothD)
        return Line.of(close.size) { index ->
            if (relative[index] == null) return@of null
            val numerator = smoothedRelative[index] ?: return@of null
            val half = (smoothedRange[index] ?: return@of null) / 2
            100 * numerator / (if (half != 0.0) half else 1e-9)
        }
    }

    /** Balance of power: where the bar closed within its own range, optionally smoothed. */
    fun balanceOfPower(
        open: DoubleArray,
        high: DoubleArray,
        low: DoubleArray,
        close: DoubleArray,
        smooth: Int = 1,
    ): Line {
        val raw = List(close.size) { index ->
            val span = high[index] - low[index]
            if (span != 0.0) (close[index] - open[index]) / span else 0.0
        }
        return if (smooth > 1) Line.from(packB.sma(raw, smooth)) else Line.from(raw)
    }

    /** Bollinger %B: where price sits across the band, 0 at the lower edge and 1 at the upper. */
    fun bollingerPercent(source: DoubleArray, period: Int = 20, multiplier: Double = 2.0): Line {
        val band = packB.bollinger(source, period, multiplier)
        return Line.of(source.size) { index ->
            val upper = band.upper[index] ?: return@of null
            val lower = band.lower[index] ?: return@of null
            (source[index] - lower) / ((upper - lower).let { if (it != 0.0) it else 1e-9 })
        }
    }

    /** Bollinger bandwidth: the band's width as a fraction of its middle. The squeeze indicator. */
    fun bollingerWidth(source: DoubleArray, period: Int = 20, multiplier: Double = 2.0): Line {
        val band = packB.bollinger(source, period, multiplier)
        return Line.of(source.size) { index ->
            val upper = band.upper[index] ?: return@of null
            val lower = band.lower[index] ?: return@of null
            val basis = band.basis[index] ?: return@of null
            if (basis != 0.0) (upper - lower) / basis else null
        }
    }

    // ══════════════════════════════════════════════════════════ volume

    /**
     * Accumulation/distribution: the running sum of the money-flow multiplier times volume.
     *
     * Every volume indicator below returns an empty line when the feed reports no volume, rather
     * than a flat zero. A flat line at zero says "no accumulation"; nothing says "no data", and
     * those are different claims.
     */
    fun accumulationDistribution(
        high: DoubleArray,
        low: DoubleArray,
        close: DoubleArray,
        volume: DoubleArray,
    ): Line {
        if (!volume.hasAny()) return Line.empty(close.size)
        var total = 0.0
        return Line.of(close.size) { index ->
            total += moneyFlow(high[index], low[index], close[index]) * volume[index]
            total
        }
    }

    /** Chaikin oscillator: the difference between a fast and a slow EMA of the A/D line. */
    fun chaikinOscillator(
        high: DoubleArray,
        low: DoubleArray,
        close: DoubleArray,
        volume: DoubleArray,
        fast: Int = 3,
        slow: Int = 10,
    ): Line {
        if (!volume.hasAny()) return Line.empty(close.size)
        var total = 0.0
        val line = List(close.size) { index ->
            total += moneyFlow(high[index], low[index], close[index]) * volume[index]
            total
        }
        val quick = packB.ema(line, fast)
        val slowly = packB.ema(line, slow)
        return Line.of(close.size) { index ->
            val a = quick[index]
            val b = slowly[index]
            if (a != null && b != null) a - b else null
        }
    }

    /**
     * Ease of movement: how far the midpoint travelled per unit of volume.
     *
     * [scale] is cosmetic — it only moves the decimal point — but it is part of the contract with
     * the web terminal, so it is here rather than hidden.
     */
    fun easeOfMovement(
        high: DoubleArray,
        low: DoubleArray,
        volume: DoubleArray,
        period: Int = 14,
        scale: Double = 100_000_000.0,
    ): Line {
        if (!volume.hasAny()) return Line.empty(high.size)
        val raw = List(high.size) { index ->
            if (index == 0) return@List 0.0
            val move = (high[index] + low[index]) / 2 - (high[index - 1] + low[index - 1]) / 2
            val span = (high[index] - low[index]).let { if (it != 0.0) it else 1e-9 }
            val box = if (volume[index] != 0.0) (volume[index] / scale) / span else 0.0
            if (box != 0.0) move / box else 0.0
        }
        val smoothed = packB.sma(raw, period)
        return Line.of(high.size) { index -> if (index < period) null else smoothed[index] }
    }

    /** Force index: the bar's price change times its volume, smoothed. */
    fun forceIndex(close: DoubleArray, volume: DoubleArray, period: Int = 13): Line {
        if (!volume.hasAny()) return Line.empty(close.size)
        val raw = List(close.size) { index ->
            if (index == 0) 0.0 else (close[index] - close[index - 1]) * volume[index]
        }
        val smoothed = packB.ema(raw, period)
        return Line.of(close.size) { index -> if (index < 1) null else smoothed[index] }
    }

    /** Klinger volume oscillator, with its signal. */
    fun klinger(
        high: DoubleArray,
        low: DoubleArray,
        close: DoubleArray,
        volume: DoubleArray,
        fast: Int = 34,
        slow: Int = 55,
        signalPeriod: Int = 13,
    ): LinePair {
        if (!volume.hasAny()) return LinePair(Line.empty(close.size), Line.empty(close.size))
        val force = DoubleArray(close.size)
        var cumulative = 0.0
        var previousRange = 0.0
        var previousTrend = 1
        for (index in 1 until close.size) {
            val now = high[index] + low[index] + close[index]
            val before = high[index - 1] + low[index - 1] + close[index - 1]
            val range = high[index] - low[index]
            val trend = if (now > before) 1 else -1
            cumulative = if (trend == previousTrend) cumulative + range else previousRange + range
            val ratio = if (cumulative != 0.0) abs(2 * (range / cumulative) - 1) else 0.0
            force[index] = volume[index] * ratio * trend * 100
            previousTrend = trend
            previousRange = range
        }
        val values = force.toList()
        val quick = packB.ema(values, fast)
        val slowly = packB.ema(values, slow)
        val line = List(close.size) { index ->
            val a = quick[index]
            val b = slowly[index]
            if (a != null && b != null) a - b else null
        }
        return LinePair(Line.from(line), Line.from(packB.emaMasked(line, signalPeriod)))
    }

    /** Price-volume trend: the running sum of fractional return times volume. */
    fun priceVolumeTrend(close: DoubleArray, volume: DoubleArray): Line {
        if (!volume.hasAny()) return Line.empty(close.size)
        var total = 0.0
        return Line.of(close.size) { index ->
            if (index == 0) return@of 0.0
            val ratio = if (close[index - 1] != 0.0) (close[index] - close[index - 1]) / close[index - 1] else 0.0
            total += ratio * volume[index]
            total
        }
    }

    private fun moneyFlow(high: Double, low: Double, close: Double): Double {
        val span = high - low
        return if (span != 0.0) ((close - low) - (high - close)) / span else 0.0
    }

    private fun DoubleArray.hasAny(): Boolean = any { it > 0 }

    private fun DoubleArray.toNullable(): List<Double?> = map { it }

    private fun List<Double>.toNullableList(): List<Double?> = map { it }

    private fun Double?.orEpsilon(): Double = if (this == null || this == 0.0) 1e-9 else this

    // ══════════════════════════════════════════════════════════ pack A primitives

    /**
     * `indicators_ext_a.js`'s helpers, exactly.
     *
     * Its averages *skip* nulls rather than carrying across them, and count only the values they
     * have actually seen. See the class KDoc for why both packs are reproduced separately.
     */
    private object packA {

        fun sma(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            var sum = 0.0
            var count = 0
            for (index in source.indices) {
                val value = source[index]
                if (value == null) {
                    sum = 0.0
                    count = 0
                    continue
                }
                sum += value
                count++
                if (index >= period) {
                    source[index - period]?.let {
                        sum -= it
                        count--
                    }
                }
                if (count >= period) out[index] = sum / period
            }
            return out.toList()
        }

        fun ema(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            val k = 2.0 / (period + 1)
            var previous: Double? = null
            var seen = 0
            for (index in source.indices) {
                val value = source[index] ?: continue
                previous = if (previous == null) value else value * k + previous * (1 - k)
                seen++
                if (seen >= period) out[index] = previous
            }
            return out.toList()
        }

        fun smma(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            var previous: Double? = null
            var sum = 0.0
            var count = 0
            for (index in source.indices) {
                val value = source[index] ?: continue
                if (previous == null) {
                    sum += value
                    count++
                    if (count == period) {
                        previous = sum / period
                        out[index] = previous
                    }
                } else {
                    previous = (previous * (period - 1) + value) / period
                    out[index] = previous
                }
            }
            return out.toList()
        }

        fun stdev(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            for (index in (period - 1) until source.size) {
                var mean = 0.0
                var complete = true
                for (step in 0 until period) {
                    val value = source[index - step]
                    if (value == null) {
                        complete = false
                        break
                    }
                    mean += value
                }
                if (!complete) continue
                mean /= period
                var total = 0.0
                for (step in 0 until period) {
                    val delta = source[index - step]!! - mean
                    total += delta * delta
                }
                out[index] = sqrt(total / period)
            }
            return out.toList()
        }

        fun linreg(source: List<Double?>, period: Int, offset: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            val sumX = (period - 1) * period / 2.0
            val sumX2 = (period - 1) * period * (2.0 * period - 1) / 6.0
            val denominator = period * sumX2 - sumX * sumX
            if (denominator == 0.0) return out.toList()
            for (index in (period - 1) until source.size) {
                var sumY = 0.0
                var sumXY = 0.0
                var complete = true
                for (step in 0 until period) {
                    val y = source[index - (period - 1) + step]
                    if (y == null) {
                        complete = false
                        break
                    }
                    sumY += y
                    sumXY += step * y
                }
                if (!complete) continue
                val slope = (period * sumXY - sumX * sumY) / denominator
                val intercept = (sumY - slope * sumX) / period
                out[index] = intercept + slope * (period - 1 + offset)
            }
            return out.toList()
        }
    }

    // ══════════════════════════════════════════════════════════ pack B primitives

    /**
     * `indicators_ext_b.js`'s helpers, exactly.
     *
     * Its averages read a null as zero and start emitting at index `period-1` regardless, which is
     * what makes an indicator built on another's output warm up when it does. See the class KDoc.
     */
    private object packB {

        fun sma(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            var sum = 0.0
            for (index in source.indices) {
                sum += source[index] ?: 0.0
                if (index >= period) sum -= source[index - period] ?: 0.0
                if (index >= period - 1) out[index] = sum / period
            }
            return out.toList()
        }

        fun ema(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            val k = 2.0 / (period + 1)
            var previous: Double? = null
            for (index in source.indices) {
                val value = source[index]
                if (value == null) {
                    out[index] = previous
                    continue
                }
                previous = if (previous == null) value else value * k + previous * (1 - k)
                if (index >= period - 1) out[index] = previous
            }
            return out.toList()
        }

        /**
         * An EMA over a series with nulls read as zero, masked back to where the input existed.
         *
         * The idiom `_ema(x.map(v => v ?? 0), p).map((v, k) => x[k] == null ? null : v)`, which
         * pack B uses for every signal line. Written once here because getting it subtly wrong in
         * four places is how a signal line ends up one bar early in three of them.
         */
        fun emaMasked(source: List<Double?>, period: Int): List<Double?> {
            val smoothed = ema(source.map { it ?: 0.0 }, period)
            return List(source.size) { if (source[it] == null) null else smoothed[it] }
        }

        fun stdev(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            for (index in (period - 1) until source.size) {
                var mean = 0.0
                for (step in 0 until period) mean += source[index - step] ?: 0.0
                mean /= period
                var total = 0.0
                for (step in 0 until period) {
                    val delta = (source[index - step] ?: 0.0) - mean
                    total += delta * delta
                }
                out[index] = sqrt(total / period)
            }
            return out.toList()
        }

        fun bollinger(source: DoubleArray, period: Int, multiplier: Double): Band {
            val values = source.map { it }
            val basis = sma(values, period)
            val deviation = stdev(values, period)
            return Band(
                basis = Line.from(basis),
                upper = Line.of(source.size) { index ->
                    val b = basis[index]
                    val d = deviation[index]
                    if (b != null && d != null) b + multiplier * d else null
                },
                lower = Line.of(source.size) { index ->
                    val b = basis[index]
                    val d = deviation[index]
                    if (b != null && d != null) b - multiplier * d else null
                },
            )
        }

        fun highest(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            for (index in (period - 1) until source.size) {
                var top = -Double.MAX_VALUE
                var found = false
                for (step in 0 until period) {
                    val value = source[index - step] ?: continue
                    found = true
                    if (value > top) top = value
                }
                if (found) out[index] = top
            }
            return out.toList()
        }

        fun lowest(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            for (index in (period - 1) until source.size) {
                var bottom = Double.MAX_VALUE
                var found = false
                for (step in 0 until period) {
                    val value = source[index - step] ?: continue
                    found = true
                    if (value < bottom) bottom = value
                }
                if (found) out[index] = bottom
            }
            return out.toList()
        }

        /** RSI over any series, Wilder-smoothed, warm-up null. */
        fun rsi(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            var averageGain = 0.0
            var averageLoss = 0.0
            for (index in 1 until source.size) {
                val now = source[index] ?: continue
                val before = source[index - 1] ?: continue
                val change = now - before
                val gain = max(change, 0.0)
                val loss = max(-change, 0.0)
                if (index <= period) {
                    averageGain += gain
                    averageLoss += loss
                    if (index == period) {
                        averageGain /= period
                        averageLoss /= period
                        out[index] = 100 - 100 / (1 + averageGain / (if (averageLoss != 0.0) averageLoss else 1e-9))
                    }
                } else {
                    averageGain = (averageGain * (period - 1) + gain) / period
                    averageLoss = (averageLoss * (period - 1) + loss) / period
                    out[index] = 100 - 100 / (1 + averageGain / (if (averageLoss != 0.0) averageLoss else 1e-9))
                }
            }
            return out.toList()
        }

        /** How many bars price has risen or fallen in a row, signed. Zero on an unchanged close. */
        fun streak(close: DoubleArray): List<Int> {
            val out = IntArray(close.size)
            for (index in 1 until close.size) {
                out[index] = when {
                    close[index] > close[index - 1] -> if (out[index - 1] > 0) out[index - 1] + 1 else 1
                    close[index] < close[index - 1] -> if (out[index - 1] < 0) out[index - 1] - 1 else -1
                    else -> 0
                }
            }
            return out.toList()
        }

        /** What percentage of the previous [period] values the current one exceeds. */
        fun percentRank(source: List<Double?>, period: Int): List<Double?> {
            val out = arrayOfNulls<Double>(source.size)
            for (index in period until source.size) {
                val value = source[index] ?: continue
                var below = 0
                var total = 0
                for (step in 1..period) {
                    val other = source[index - step] ?: continue
                    total++
                    if (other < value) below++
                }
                if (total > 0) out[index] = 100.0 * below / total
            }
            return out.toList()
        }
    }
}
